/**
 * Explicit physical-column privacy classifications.
 *
 * This file deliberately contains no column-name inference or fallback.
 * A schema change therefore fails exact-set tests until its physical column
 * is consciously added to one class below.
 */

export const PRIVACY_FIELD_CLASSES = [
	"non_personal",
	"subject_identifier",
	"direct_identifier",
	"credential",
	"content",
	"network_identifier",
	"financial",
	"behavioral",
	"sensitive",
	"operational",
] as const;

export type PrivacyFieldClass = (typeof PRIVACY_FIELD_CLASSES)[number];

export interface PostgresPrivacyFieldClassification {
	readonly subjectLocator:
		| "organization"
		| "workspace"
		| "user"
		| "contact"
		| "account"
		| "parent"
		| "shared_organizations"
		| "none";
	readonly columns: Readonly<
		Partial<Record<PrivacyFieldClass, readonly string[]>>
	>;
}

export const POSTGRES_PRIVACY_FIELD_CLASSIFICATIONS = {
	"postgres:auth.account": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "userId", "accountId", "providerId"],
			credential: ["accessToken", "refreshToken", "idToken", "password"],
			behavioral: ["createdAt", "updatedAt"],
			sensitive: ["scope"],
			operational: ["accessTokenExpiresAt", "refreshTokenExpiresAt"],
		},
	},
	"postgres:auth.apikey": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"configId",
				"referenceId",
				"organizationId",
				"principalId",
			],
			credential: ["key"],
			content: ["name", "metadata"],
			behavioral: ["lastRefillAt", "requestCount", "createdAt", "updatedAt"],
			sensitive: ["permissions"],
			operational: [
				"start",
				"prefix",
				"refillInterval",
				"refillAmount",
				"enabled",
				"rateLimitEnabled",
				"rateLimitTimeWindow",
				"rateLimitMax",
				"remaining",
				"lastRequest",
				"expiresAt",
				"credentialVersion",
			],
		},
	},
	"postgres:auth.invitation": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "inviterId", "organizationId"],
			direct_identifier: ["email"],
			behavioral: ["createdAt"],
			operational: ["role", "status", "expiresAt", "issuerCredentialVersion"],
		},
	},
	"postgres:auth.member": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "userId", "organizationId"],
			behavioral: ["createdAt"],
			sensitive: ["role"],
		},
	},
	"postgres:auth.organization": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "slug"],
			content: ["name", "logo", "metadata"],
			behavioral: ["deletion_requested_at", "tombstoned_at", "createdAt"],
			operational: ["lifecycle_status"],
		},
	},
	"postgres:auth.organization_creation_reservation": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "user_id", "slug"],
			behavioral: ["created_at"],
			operational: ["expires_at"],
		},
	},
	"postgres:auth.session": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "userId", "activeOrganizationId"],
			credential: ["token"],
			network_identifier: ["ipAddress", "userAgent"],
			behavioral: ["createdAt", "updatedAt"],
			sensitive: ["impersonatedBy"],
			operational: ["expiresAt"],
		},
	},
	"postgres:auth.user": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id"],
			direct_identifier: ["name", "email", "image"],
			behavioral: ["createdAt", "updatedAt"],
			sensitive: ["role", "banned", "banReason", "banExpires"],
			operational: ["emailVerified", "credentialVersion"],
		},
	},
	"postgres:auth.verification": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id"],
			direct_identifier: ["identifier"],
			credential: ["value"],
			behavioral: ["createdAt", "updatedAt"],
			operational: ["expiresAt"],
		},
	},
	"postgres:public.account_revocation_jobs": {
		subjectLocator: "account",
		columns: {
			subject_identifier: ["id", "account_id", "organization_id"],
			credential: ["access_token_ciphertext", "refresh_token_ciphertext"],
			content: ["last_error", "provider_response"],
			behavioral: [
				"request_may_have_been_sent_at",
				"created_at",
				"updated_at",
				"completed_at",
			],
			operational: [
				"platform",
				"source_token_version",
				"status",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.ad_accounts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"social_account_id",
				"platform_ad_account_id",
			],
			content: ["name", "metadata", "sync_last_error", "sync_last_error_class"],
			financial: ["currency"],
			behavioral: [
				"last_sync_at",
				"next_sync_at",
				"sync_started_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"platform",
				"timezone",
				"status",
				"sync_generation",
				"sync_lease_expires_at",
				"sync_attempts",
			],
		},
	},
	"postgres:public.ad_audience_users": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: ["id", "audience_id", "email_hash", "phone_hash"],
			behavioral: ["added_at"],
		},
	},
	"postgres:public.ad_audiences": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"ad_account_id",
				"platform_audience_id",
				"source_audience_id",
			],
			content: ["name", "description", "metadata"],
			behavioral: ["created_at", "updated_at"],
			sensitive: ["lookalike_spec", "retargeting_rule"],
			operational: ["platform", "type", "size", "status"],
		},
	},
	"postgres:public.ad_campaigns": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"ad_account_id",
				"platform_campaign_id",
			],
			content: ["name", "metadata"],
			financial: ["daily_budget_cents", "lifetime_budget_cents", "currency"],
			behavioral: ["created_at", "updated_at"],
			operational: [
				"platform",
				"objective",
				"status",
				"start_date",
				"end_date",
				"is_external",
			],
		},
	},
	"postgres:public.ad_creation_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"ad_account_id",
				"authority_key_id",
				"authority_principal_id",
				"authority_user_id",
				"authority_member_id",
				"authority_session_id",
				"authority_workspace_id",
				"operation_key_hash",
				"request_hash",
				"platform_campaign_id",
				"platform_ad_set_id",
				"platform_creative_id",
				"platform_ad_id",
				"local_campaign_id",
				"local_ad_id",
			],
			content: ["request_payload", "last_error"],
			behavioral: [
				"authority_admitted_at",
				"authority_revoked_at",
				"request_may_have_been_sent_at",
				"created_at",
				"updated_at",
				"completed_at",
			],
			operational: [
				"usage_reservation_id",
				"authority_principal_type",
				"authority_requires_all_workspace_scope",
				"authority_credential_version",
				"authority_revision",
				"kind",
				"status",
				"phase",
				"platform",
				"lease_token",
				"lease_expires_at",
				"attempts",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.ad_mutation_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"target_id",
				"authority_key_id",
				"authority_principal_id",
				"authority_user_id",
				"authority_member_id",
				"authority_session_id",
				"authority_workspace_id",
				"operation_key_hash",
				"request_hash",
			],
			content: ["request_payload", "last_error"],
			financial: [],
			behavioral: [
				"authority_admitted_at",
				"authority_revoked_at",
				"request_may_have_been_sent_at",
				"provider_confirmed_at",
				"created_at",
				"updated_at",
				"completed_at",
			],
			operational: [
				"usage_reservation_id",
				"requires_live_authority",
				"authority_principal_type",
				"authority_requires_all_workspace_scope",
				"authority_credential_version",
				"authority_revision",
				"target_type",
				"kind",
				"platform",
				"status",
				"phase",
				"lease_token",
				"lease_expires_at",
				"attempts",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.ad_metrics": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "ad_id"],
			financial: ["spend_cents", "cpc_cents", "cpm_cents"],
			behavioral: [
				"impressions",
				"reach",
				"clicks",
				"conversions",
				"video_views",
				"engagement",
				"collected_at",
				"created_at",
			],
			sensitive: ["demographics"],
			operational: ["date", "ctr"],
		},
	},
	"postgres:public.ad_sync_logs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"ad_account_id",
			],
			content: ["error"],
			behavioral: ["started_at", "completed_at"],
			operational: [
				"platform",
				"sync_type",
				"ads_created",
				"ads_updated",
				"metrics_updated",
			],
		},
	},
	"postgres:public.ads": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"campaign_id",
				"ad_account_id",
				"platform_ad_id",
				"boost_post_target_id",
				"boost_external_post_id",
				"boost_platform_post_id",
			],
			content: [
				"name",
				"headline",
				"body",
				"metadata",
				"metrics_poll_last_error",
				"metrics_poll_last_error_class",
			],
			network_identifier: ["link_url", "image_url", "video_url"],
			financial: ["daily_budget_cents", "lifetime_budget_cents"],
			behavioral: [
				"call_to_action",
				"duration_days",
				"metrics_updated_at",
				"metrics_next_poll_at",
				"metrics_poll_started_at",
				"created_at",
				"updated_at",
			],
			sensitive: ["targeting"],
			operational: [
				"platform",
				"status",
				"start_date",
				"end_date",
				"is_external",
				"metrics_poll_generation",
				"metrics_poll_lease_expires_at",
				"metrics_poll_attempts",
			],
		},
	},
	"postgres:public.ai_agents": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"kb_id",
				"handoff_principal_id",
			],
			content: ["name"],
			behavioral: ["created_at", "updated_at"],
			sensitive: ["persona", "guardrails"],
			operational: [
				"provider",
				"model",
				"handoff_strategy",
				"temperature",
				"max_tokens",
				"enabled",
			],
		},
	},
	"postgres:public.ai_knowledge_bases": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: [
				"name",
				"description",
				"embedding_provider",
				"embedding_model",
				"embedding_dimensions",
			],
			behavioral: ["created_at", "updated_at"],
		},
	},
	"postgres:public.ai_knowledge_chunks": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"document_id",
				"kb_id",
				"organization_id",
				"scope_key",
				"content_hash",
			],
			content: ["content", "embedding"],
			behavioral: ["token_count", "created_at"],
			operational: ["chunk_index"],
		},
	},
	"postgres:public.ai_knowledge_documents": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"kb_id",
				"organization_id",
				"scope_key",
				"source_media_id",
				"attempt_id",
				"content_hash",
			],
			content: ["source_text", "title", "last_error_code", "last_error"],
			network_identifier: ["source_url"],
			behavioral: [
				"attempt_count",
				"claimed_at",
				"last_crawled_at",
				"completed_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"source_type",
				"status",
				"next_attempt_at",
				"deadline_at",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.api_request_logs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "api_key_id"],
			network_identifier: ["path"],
			behavioral: ["response_time_ms", "created_at"],
			operational: ["method", "status_code", "billable"],
		},
	},
	"postgres:public.auto_post_feed_items": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"operation_id",
				"rule_id",
				"organization_id",
				"canonical_feed_item_id",
				"source_item_id",
				"post_id",
			],
			content: ["error"],
			network_identifier: ["canonical_url"],
			behavioral: ["published_at", "created_at", "completed_at"],
			operational: ["status"],
		},
	},
	"postgres:public.auto_post_rules": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"account_ids",
			],
			content: ["name", "content_template", "last_error", "consecutive_errors"],
			network_identifier: ["feed_url", "append_feed_url", "last_processed_url"],
			behavioral: ["last_processed_at", "created_at", "updated_at"],
			operational: [
				"polling_interval_minutes",
				"status",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.automation_bindings": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"social_account_id",
				"automation_id",
			],
			content: ["config", "sync_error", "sync_error_class"],
			behavioral: [
				"sync_started_at",
				"sync_request_may_have_been_sent_at",
				"last_synced_at",
				"sync_error_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"channel",
				"binding_type",
				"status",
				"desired_active",
				"delete_after_sync",
				"sync_revision",
				"last_synced_revision",
				"sync_attempts",
				"sync_dispatch_generation",
				"sync_next_attempt_at",
				"sync_lease_expires_at",
			],
		},
	},
	"postgres:public.automation_contact_controls": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"contact_id",
				"automation_id",
				"paused_by_user_id",
			],
			content: ["pause_reason"],
			behavioral: ["created_at", "updated_at"],
			operational: ["paused_until"],
		},
	},
	"postgres:public.automation_conversion_events": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"automation_id",
				"run_id",
				"contact_id",
				"occurrence_id",
				"social_account_id",
				"conversation_id",
			],
			content: ["event_name", "metadata", "last_dispatch_error"],
			financial: ["value", "currency"],
			behavioral: [
				"event_depth",
				"next_dispatch_at",
				"dispatched_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"channel",
				"dispatch_status",
				"dispatch_attempts",
				"dispatch_lease_token",
				"dispatch_lease_expires_at",
				"dispatch_deadline_at",
			],
		},
	},
	"postgres:public.automation_effects": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"node_execution_id",
				"organization_id",
				"scope_key",
				"provider_reference",
			],
			content: ["result", "last_error"],
			behavioral: [
				"request_may_have_been_sent_at",
				"created_at",
				"updated_at",
				"completed_at",
			],
			operational: [
				"effect_key",
				"kind",
				"provider_idempotency_key",
				"status",
				"attempts",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.automation_entrypoint_daily_counts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"entrypoint_id",
			],
			behavioral: ["count", "updated_at"],
			operational: ["day"],
		},
	},
	"postgres:public.automation_entrypoints": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"automation_id",
				"social_account_id",
			],
			content: ["config", "filters"],
			behavioral: ["created_at", "updated_at"],
			operational: [
				"channel",
				"kind",
				"status",
				"allow_reentry",
				"reentry_cooldown_min",
				"daily_cap",
				"priority",
				"specificity",
			],
		},
	},
	"postgres:public.automation_node_executions": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "run_id", "organization_id", "scope_key"],
			content: ["result", "error"],
			behavioral: ["claimed_at", "completed_at", "updated_at"],
			operational: [
				"run_revision",
				"visit_ordinal",
				"node_key",
				"status",
				"attempts",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.automation_runs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"automation_id",
				"organization_id",
				"scope_key",
				"entrypoint_id",
				"binding_id",
				"contact_id",
				"conversation_id",
				"trigger_occurrence_id",
			],
			content: ["context", "exit_reason"],
			behavioral: ["started_at", "completed_at", "updated_at"],
			operational: [
				"revision",
				"status",
				"current_node_key",
				"current_port_key",
				"waiting_until",
				"waiting_for",
			],
		},
	},
	"postgres:public.automation_scheduled_jobs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"occurrence_id",
				"organization_id",
				"scope_key",
				"run_id",
				"automation_id",
				"entrypoint_id",
			],
			content: ["payload", "error"],
			behavioral: ["run_at", "claimed_at", "effect_started_at", "created_at"],
			operational: [
				"job_type",
				"status",
				"attempts",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.automation_secrets": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"automation_id",
				"action_id",
				"key_id",
			],
			credential: ["ciphertext"],
			behavioral: ["created_at", "updated_at"],
			operational: ["node_key", "kind"],
		},
	},
	"postgres:public.automation_step_runs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"run_id",
				"automation_id",
				"organization_id",
				"scope_key",
			],
			content: ["payload", "error"],
			behavioral: ["duration_ms", "executed_at"],
			operational: [
				"node_key",
				"node_kind",
				"entered_via_port_key",
				"exited_via_port_key",
				"outcome",
			],
		},
	},
	"postgres:public.automation_webhook_receipts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"automation_id",
				"entrypoint_id",
				"request_digest",
				"run_id",
			],
			content: ["last_error"],
			network_identifier: ["payload_ciphertext"],
			behavioral: ["received_at", "completed_at"],
			operational: [
				"signature_timestamp",
				"status",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
				"expires_at",
			],
		},
	},
	"postgres:public.automations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: [
				"name",
				"description",
				"graph",
				"created_from_template",
				"template_config",
				"validation_errors",
			],
			behavioral: [
				"last_validated_at",
				"created_by",
				"created_at",
				"updated_at",
			],
			operational: [
				"channel",
				"status",
				"total_enrolled",
				"total_completed",
				"total_exited",
				"total_failed",
			],
		},
	},
	"postgres:public.billing_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "billing_period_id"],
			content: ["description", "last_error", "last_error_class"],
			financial: [
				"stripe_customer_id",
				"stripe_subscription_id",
				"stripe_invoice_id",
				"stripe_invoice_item_id",
				"amount_cents",
				"currency",
			],
			behavioral: [
				"operator_retry_requested_at",
				"created_at",
				"updated_at",
				"completed_at",
			],
			operational: [
				"kind",
				"status",
				"invoice_idempotency_key",
				"idempotency_key",
				"attempt_revision",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.billing_operation_attempts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "billing_operation_id"],
			content: ["description", "provider_evidence"],
			financial: [
				"stripe_customer_id",
				"stripe_subscription_id",
				"stripe_invoice_id",
				"stripe_invoice_item_id",
				"amount_cents",
				"currency",
			],
			behavioral: [
				"request_may_have_been_sent_at",
				"created_at",
				"resolved_at",
			],
			operational: ["revision", "status", "idempotency_key"],
		},
	},
	"postgres:public.stripe_organization_leases": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["organization_id"],
			behavioral: ["updated_at"],
			operational: ["lease_token", "owner_event_id", "lease_expires_at"],
		},
	},
	"postgres:public.billing_outbox": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			content: ["payload", "last_error", "last_error_class"],
			behavioral: [
				"processed_at",
				"manual_review_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"kind",
				"status",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.billing_periods": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "invoice_id"],
			financial: [
				"stripe_customer_id",
				"stripe_subscription_id",
				"stripe_product_id",
				"stripe_price_id",
				"stripe_price_role",
				"rate_card_version",
				"tax_behavior",
				"tax_code",
				"discountable",
				"billable",
				"quota_mode",
				"provider_cycle_anchor",
				"period_start",
				"period_end",
				"cycle_allowance",
				"included_units",
				"price_per_thousand_units_cents",
				"base_price_cents",
				"currency",
				"committed_units_snapshot",
				"effective_included_units_snapshot",
				"overage_units_snapshot",
				"amount_cents_snapshot",
				"stripe_invoice_id",
			],
			behavioral: [
				"closed_at",
				"claimed_at",
				"settled_at",
				"released_at",
				"written_off_at",
				"voided_at",
				"created_at",
				"updated_at",
			],
			content: ["write_off_reason", "write_off_evidence"],
			operational: ["source", "state", "release_count", "revision"],
		},
	},
	"postgres:public.broadcast_recipients": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"broadcast_id",
				"contact_id",
				"contact_identifier_hash",
				"message_id",
			],
			direct_identifier: ["contact_identifier"],
			content: ["variables", "error"],
			behavioral: [
				"pii_erased_at",
				"claimed_at",
				"request_may_have_been_sent_at",
				"sent_at",
				"created_at",
			],
			operational: ["status", "delivery_state"],
		},
	},
	"postgres:public.broadcasts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"social_account_id",
			],
			content: [
				"name",
				"description",
				"message_text",
				"template_name",
				"template_language",
				"template_components",
			],
			behavioral: [
				"recipient_count",
				"sent_count",
				"failed_count",
				"scheduled_at",
				"completed_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"platform",
				"status",
				"revision",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.connection_logs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "social_account_id"],
			content: ["message", "snapshot"],
			behavioral: ["event", "created_at"],
			operational: ["platform"],
		},
	},
	"postgres:public.contact_channels": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"contact_id",
				"social_account_id",
				"identifier_hash",
				"identity_key_fingerprint",
			],
			direct_identifier: ["identifier_ciphertext"],
			behavioral: ["created_at"],
			operational: ["platform"],
		},
	},
	"postgres:public.contact_consent_events": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"contact_id",
				"workspace_id",
				"scope_key",
				"logical_identifier_hash",
				"identifier_hash",
			],
			direct_identifier: ["identifier_masked"],
			sensitive: [
				"ordering_hlc",
				"ordering_region",
				"channel",
				"purpose",
				"status",
				"identifier_key_version",
				"source",
				"occurred_at",
				"evidence",
				"policy_version",
				"jurisdiction",
				"created_at",
			],
		},
	},
	"postgres:public.contact_consent_states": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"logical_identifier_hash",
				"identifier_hash",
				"identity_key_fingerprint",
				"last_event_id",
			],
			sensitive: [
				"channel",
				"purpose",
				"identifier_key_version",
				"status",
				"source",
				"occurred_at",
				"policy_version",
				"jurisdiction",
				"last_ordering_hlc",
				"last_ordering_region",
				"updated_at",
			],
		},
	},
	"postgres:public.contact_segment_memberships": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"contact_id",
				"segment_id",
				"organization_id",
				"scope_key",
				"created_by_user_id",
			],
			behavioral: ["created_at"],
			operational: ["segment_is_dynamic", "source"],
		},
	},
	"postgres:public.contact_subscription_events": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"contact_id",
				"list_id",
				"actor_id",
				"merged_from_contact_id",
			],
			sensitive: [
				"ingestion_sequence",
				"type",
				"source",
				"occurred_at",
				"created_at",
			],
		},
	},
	"postgres:public.contact_subscriptions": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"organization_id",
				"scope_key",
				"contact_id",
				"list_id",
				"last_event_id",
			],
			sensitive: [
				"state",
				"subscribed_at",
				"unsubscribed_at",
				"source",
				"last_event_sequence",
				"updated_at",
			],
		},
	},
	"postgres:public.contacts": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"name_hash",
				"name_search_tokens",
				"email_hash",
				"email_search_tokens",
				"phone_hash",
				"phone_search_tokens",
				"search_identity_key_fingerprint",
			],
			direct_identifier: [
				"name_ciphertext",
				"email_ciphertext",
				"phone_ciphertext",
			],
			behavioral: ["created_at", "updated_at"],
			sensitive: ["metadata_ciphertext", "tags", "opted_in"],
		},
	},
	"postgres:public.content_templates": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["name", "description", "content", "tags"],
			behavioral: ["created_at", "updated_at"],
			operational: ["platform_overrides"],
		},
	},
	"postgres:public.cross_post_actions": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"operation_id",
				"organization_id",
				"scope_key",
				"post_id",
				"source_target_id",
				"target_account_id",
				"result_post_id",
			],
			content: ["content", "error"],
			behavioral: [
				"action_type",
				"executed_at",
				"readiness_checks",
				"request_may_have_been_sent_at",
				"completed_at",
				"created_at",
			],
			operational: [
				"source_platform",
				"target_platform",
				"delay_minutes",
				"status",
				"scheduled_for",
				"next_attempt_at",
				"attempts",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.custom_field_definitions": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"slug",
			],
			content: ["name"],
			behavioral: ["created_at", "updated_at"],
			operational: ["type", "options"],
		},
	},
	"postgres:public.custom_field_values": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"definition_id",
				"contact_id",
				"organization_id",
				"scope_key",
				"definition_scope_key",
			],
			behavioral: ["created_at", "updated_at"],
			sensitive: ["value"],
		},
	},
	"postgres:public.dunning_events": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"invoice_id",
				"provider_message_id",
				"deactivation_operation_id",
			],
			content: [
				"last_error",
				"deactivation_provider_response",
				"deactivation_last_error",
			],
			financial: ["stripe_invoice_id"],
			behavioral: [
				"event",
				"due_at",
				"claimed_at",
				"deactivation_requested_at",
				"deactivation_confirmed_at",
				"sent_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"status",
				"delivery_idempotency_key",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"deadline_at",
				"lease_expires_at",
				"deactivation_status",
			],
		},
	},
	"postgres:public.email_deliveries": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"auth_user_id",
				"subject_user_id",
				"envelope_key_id",
				"provider_message_id",
			],
			content: ["envelope_ciphertext", "error"],
			behavioral: [
				"next_dispatch_at",
				"queued_at",
				"request_may_have_been_sent_at",
				"created_at",
				"completed_at",
				"redacted_at",
			],
			operational: [
				"intent",
				"status",
				"provider_attempts",
				"lease_token",
				"lease_expires_at",
				"next_attempt_at",
				"deadline_at",
				"dispatch_attempts",
				"dispatch_lease_token",
				"dispatch_lease_expires_at",
				"expires_at",
				"purge_at",
			],
		},
	},
	"postgres:public.erasure_holds": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "subject_id", "organization_tombstone_id"],
			content: ["reason_code"],
			network_identifier: ["evidence_ciphertext"],
			behavioral: [
				"placed_by",
				"placed_at",
				"released_by",
				"released_at",
				"created_at",
			],
			sensitive: [
				"reason_summary",
				"legal_authority_ref",
				"release_reason_summary",
				"evidence_redacted_at",
			],
			operational: ["subject_kind"],
		},
	},
	"postgres:public.external_posts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"social_account_id",
				"platform_post_id",
			],
			content: [
				"content",
				"preview_last_error",
				"platform_data",
				"metrics_poll_last_error",
				"metrics_poll_last_error_class",
				"notes",
			],
			network_identifier: [
				"platform_url",
				"media_urls",
				"thumbnail_url",
				"preview_thumbnail_key",
				"preview_storage_bucket_locator",
				"preview_thumbnail_url",
			],
			behavioral: [
				"preview_storage_provider",
				"preview_storage_region",
				"preview_status",
				"preview_attempts",
				"preview_next_retry_at",
				"metrics_updated_at",
				"metrics_next_poll_at",
				"metrics_poll_started_at",
				"published_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"platform",
				"media_type",
				"metrics",
				"metrics_poll_generation",
				"metrics_poll_lease_expires_at",
				"metrics_poll_attempts",
			],
		},
	},
	"postgres:public.external_subject_cleanup_jobs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"subject_id",
			],
			credential: ["credential_ciphertext"],
			content: ["last_error"],
			network_identifier: ["bucket", "object_locator", "prefix_locator"],
			behavioral: ["completed_at", "created_at", "updated_at"],
			operational: [
				"subject_kind",
				"operation",
				"external_provider",
				"provider_ref",
				"cursor",
				"status",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
				"deadline_at",
				"purge_at",
			],
		},
	},
	"postgres:public.financial_retention_receipts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"source_id",
				"organization_tombstone_id",
				"provider_reference_digest",
			],
			financial: [
				"period_start",
				"period_end",
				"amount_cents",
				"currency",
				"quantity",
				"included_quantity",
				"overage_quantity",
			],
			behavioral: ["retention_anchor_at", "recorded_at"],
			operational: [
				"source_kind",
				"retention_class",
				"status",
				"retained_until",
			],
		},
	},
	"postgres:public.idea_activity": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"idea_id",
				"organization_id",
				"actor_principal_id",
			],
			content: ["metadata"],
			behavioral: ["action", "created_at"],
		},
	},
	"postgres:public.idea_comments": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"idea_id",
				"organization_id",
				"author_principal_id",
				"parent_id",
			],
			content: ["content"],
			behavioral: ["created_at", "updated_at"],
		},
	},
	"postgres:public.idea_conversion_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"idea_id",
				"organization_id",
				"scope_key",
				"post_id",
			],
			content: ["last_error"],
			behavioral: ["created_at", "updated_at", "completed_at"],
			operational: [
				"idempotency_key",
				"status",
				"revision",
				"attempts",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.idea_groups": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["name", "color"],
			behavioral: ["created_at", "updated_at"],
			operational: ["position", "is_default", "revision"],
		},
	},
	"postgres:public.idea_media": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"idea_id",
				"media_id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["alt"],
			behavioral: ["created_at"],
			operational: ["type", "position", "delete_with_idea"],
		},
	},
	"postgres:public.idea_tags": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"idea_id",
				"tag_id",
				"tag_scope_key",
				"organization_id",
				"scope_key",
			],
		},
	},
	"postgres:public.ideas": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"group_id",
				"group_scope_key",
				"converted_to_post_id",
			],
			content: ["title", "content"],
			behavioral: ["assigned_to", "created_at", "updated_at"],
			operational: ["position", "revision"],
		},
	},
	"postgres:public.idempotency_receipts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"request_hash",
				"resource_id",
			],
			content: ["response_content_type", "last_error"],
			network_identifier: ["route", "route_hash", "response_body_ciphertext"],
			behavioral: ["created_at", "completed_at", "updated_at"],
			operational: [
				"method",
				"idempotency_key",
				"state",
				"response_status",
				"expires_at",
			],
		},
	},
	"postgres:public.inbound_webhook_events": {
		subjectLocator: "shared_organizations",
		columns: {
			subject_identifier: ["id", "payload_key_id", "organization_ids"],
			content: ["content_type", "signature_metadata", "last_error"],
			network_identifier: ["payload_ciphertext"],
			behavioral: [
				"received_at",
				"claimed_at",
				"processed_at",
				"manual_review_until",
				"redacted_at",
			],
			operational: [
				"provider",
				"delivery_key",
				"status",
				"attempts",
				"expires_at",
			],
		},
	},
	"postgres:public.inbox_conversation_notes": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"conversation_id",
				"organization_id",
				"actor_id",
				"user_id",
			],
			content: ["text"],
			behavioral: ["actor_type", "created_at", "updated_at"],
		},
	},
	"postgres:public.inbox_conversations": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"account_id",
				"platform_conversation_id",
				"post_id",
				"post_platform_id",
				"participant_platform_id",
				"contact_id",
				"contact_subject_locator",
				"contact_subject_identity_key_fingerprint",
				"assigned_user_id",
			],
			direct_identifier: [
				"participant_name",
				"participant_avatar",
				"participant_avatar_object_key",
			],
			content: [
				"participant_metadata",
				"labels",
				"last_message_text",
				"last_message_direction",
			],
			behavioral: [
				"unread_count",
				"message_count",
				"last_message_at",
				"closed_at",
				"content_redacted_at",
				"created_at",
				"updated_at",
			],
			sensitive: ["sentiment_avg"],
			operational: [
				"platform",
				"type",
				"status",
				"priority",
				"content_expires_at",
			],
		},
	},
	"postgres:public.inbox_event_effects": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"account_id",
				"platform_event_id",
			],
			content: ["error", "replay_payload"],
			behavioral: [
				"started_at",
				"effect_started_at",
				"completed_at",
				"last_enqueued_at",
				"updated_at",
			],
			operational: [
				"effect",
				"status",
				"attempts",
				"lease_token",
				"lease_expires_at",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.inbox_messages": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"conversation_id",
				"organization_id",
				"scope_key",
				"account_id",
				"platform_message_id",
				"author_platform_id",
			],
			direct_identifier: ["author_name", "author_avatar_url"],
			content: ["text", "attachments", "platform_data"],
			behavioral: ["content_redacted_at", "created_at"],
			sensitive: ["sentiment_score", "classification"],
			operational: ["platform", "direction", "is_hidden", "is_liked"],
		},
	},
	"postgres:public.invite_token_workspaces": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"organization_id",
				"invite_token_id",
				"workspace_id",
				"scope_key",
			],
			behavioral: ["created_at"],
			operational: ["scope_mode"],
		},
	},
	"postgres:public.invite_tokens": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"created_by_principal_id",
				"redeemed_by_user_id",
			],
			credential: ["token_hash"],
			behavioral: ["created_by", "used_by", "used_at", "created_at"],
			operational: [
				"issuer_credential_version",
				"scope_mode",
				"role",
				"used",
				"expires_at",
			],
		},
	},
	"postgres:public.invoices": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			credential: ["stripe_hosted_url"],
			financial: [
				"period_start",
				"period_end",
				"base_price_cents",
				"api_calls_count",
				"api_calls_included",
				"overage_calls",
				"overage_cost_cents",
				"total_cents",
				"currency",
				"stripe_invoice_id",
			],
			behavioral: [
				"first_payment_failed_at",
				"finalized_at",
				"paid_at",
				"created_at",
				"updated_at",
			],
			operational: ["status"],
		},
	},
	"postgres:public.landing_pages": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"slug",
				"automation_id",
			],
			content: ["title", "config"],
			behavioral: ["conversions", "created_at", "updated_at"],
			operational: ["visits", "enabled"],
		},
	},
	"postgres:public.media": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"storage_location_id",
				"workspace_id",
				"scope_key",
			],
			content: ["filename", "thumbnail_last_error", "deletion_last_error"],
			network_identifier: [
				"storage_key",
				"storage_bucket_locator",
				"url",
				"thumbnail_key",
				"thumbnail_storage_bucket_locator",
				"thumbnail_url",
			],
			behavioral: [
				"thumbnail_next_retry_at",
				"original_deleted_at",
				"deletion_requested_at",
				"original_deletion_confirmed_at",
				"thumbnail_deletion_confirmed_at",
				"deletion_next_retry_at",
				"duration",
				"uploaded_by",
				"created_at",
			],
			operational: [
				"mime_type",
				"size",
				"storage_provider",
				"storage_region",
				"storage_credential_version",
				"thumbnail_storage_provider",
				"thumbnail_storage_region",
				"thumbnail_status",
				"thumbnail_attempts",
				"deletion_attempts",
				"width",
				"height",
				"status",
			],
		},
	},
	"postgres:public.notification_preferences": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "user_id", "organization_id", "weekly_digest"],
			behavioral: [
				"account_disconnects",
				"streak_warnings",
				"created_at",
				"updated_at",
			],
			operational: [
				"post_failures",
				"post_published",
				"payment_alerts",
				"usage_alerts",
				"marketing",
			],
		},
	},
	"postgres:public.notifications": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "user_id", "organization_id", "occurrence_id"],
			content: ["title", "body"],
			behavioral: ["read", "created_at"],
			operational: ["type", "data"],
		},
	},
	"postgres:public.one_time_capabilities": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			credential: ["payload_ciphertext"],
			behavioral: ["created_at", "claimed_at"],
			operational: ["kind", "expires_at"],
		},
	},
	"postgres:public.operator_resolution_evidence": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"target_id",
				"reason_digest",
				"actor_user_id",
			],
			content: ["reason_code", "before_state", "after_state"],
			behavioral: [
				"action",
				"target_updated_at_before",
				"target_updated_at_after",
				"resolved_at",
			],
			operational: ["target_type"],
		},
	},
	"postgres:public.operator_resolution_notes": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["evidence_id", "organization_id"],
			network_identifier: ["note_ciphertext"],
			behavioral: ["created_at"],
			operational: ["expires_at"],
		},
	},
	"postgres:public.org_streaks": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			behavioral: [
				"streak_started_at",
				"last_post_at",
				"current_streak_days",
				"best_streak_days",
				"total_streaks_broken",
				"warning_email_sent_at",
				"created_at",
				"updated_at",
			],
		},
	},
	"postgres:public.organization_principals": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "member_id"],
			content: ["service_name"],
			behavioral: ["disabled_at", "created_at", "updated_at"],
			operational: ["kind", "scope_mode", "lifecycle_status"],
		},
	},
	"postgres:public.organization_settings": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"organization_id",
				"require_workspace_id",
				"updated_by_user_id",
				"updated_by_api_key_id",
			],
			behavioral: ["created_at", "updated_at"],
			operational: ["revision"],
		},
	},
	"postgres:public.organization_subscriptions": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			financial: [
				"current_period_start",
				"current_period_end",
				"stripe_customer_id",
				"stripe_checkout_session_id",
				"stripe_subscription_id",
				"stripe_metered_item_id",
				"cancel_at_period_end",
			],
			behavioral: [
				"delinquent_at",
				"grace_ends_at",
				"trial_ends_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"status",
				"source",
				"ai_enabled",
				"daily_tool_limit_override",
			],
		},
	},
	"postgres:public.post_analytics": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "post_target_id"],
			behavioral: [
				"impressions",
				"reach",
				"likes",
				"comments",
				"shares",
				"saves",
				"clicks",
				"views",
				"collected_at",
			],
			operational: ["platform", "observation_window_start"],
		},
	},
	"postgres:public.post_recycling_configs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "source_post_id"],
			content: ["content_variations", "content_variation_index", "last_error"],
			behavioral: [
				"expire_count",
				"recycle_count",
				"next_recycle_at",
				"last_recycled_at",
				"retry_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"enabled",
				"gap",
				"gap_freq",
				"start_date",
				"expire_date",
				"processing_state",
				"attempts",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.post_tags": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"post_id",
				"tag_id",
				"organization_id",
				"scope_key",
				"tag_scope_key",
			],
		},
	},
	"postgres:public.post_targets": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"post_id",
				"social_account_id",
				"publish_operation_id",
				"attempt_id",
				"platform_post_id",
				"provider_operation_id",
			],
			content: ["provider_effects", "error", "error_code", "error_detail"],
			network_identifier: ["platform_url"],
			behavioral: [
				"claimed_at",
				"request_may_have_been_sent_at",
				"next_reconcile_at",
				"published_at",
				"updated_at",
			],
			operational: [
				"platform",
				"status",
				"delivery_state",
				"lease_expires_at",
				"provider_disposition",
				"provider_state",
				"reconcile_attempts",
			],
		},
	},
	"postgres:public.post_threads": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			behavioral: ["created_at", "updated_at"],
			operational: ["revision"],
		},
	},
	"postgres:public.posts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"recycled_from_id",
				"thread_group_id",
				"publish_lease_id",
			],
			content: [
				"content",
				"metrics_snapshot",
				"metrics_poll_last_error",
				"metrics_poll_last_error_class",
				"notes",
				"terminal_reason",
			],
			behavioral: [
				"scheduled_at",
				"published_at",
				"created_by",
				"metrics_collected_at",
				"metrics_next_poll_at",
				"metrics_refresh_started_at",
				"thread_position",
				"thread_delay_ms",
				"created_at",
				"updated_at",
			],
			operational: [
				"status",
				"revision",
				"timezone",
				"platform_overrides",
				"metrics_poll_attempts",
				"metrics_refresh_window_start",
				"metrics_refresh_lease_expires_at",
				"publish_lease_expires_at",
				"publish_attempts",
			],
		},
	},
	"postgres:public.principal_workspace_grants": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"organization_id",
				"principal_id",
				"workspace_id",
				"scope_key",
			],
			behavioral: ["granted_at"],
			operational: ["scope_mode"],
		},
	},
	"postgres:public.public_growth_events": {
		subjectLocator: "contact",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"scope_key",
				"qr_code_id",
				"landing_page_id",
				"contact_id",
				"contact_organization_id",
				"contact_scope_key",
				"automation_id",
				"automation_organization_id",
				"automation_scope_key",
				"idempotency_hash",
			],
			content: ["last_error"],
			network_identifier: ["ref_url_id"],
			behavioral: ["event_type", "completed_at", "occurred_at", "updated_at"],
			operational: [
				"status",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.publish_attempts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"publish_operation_id",
				"post_target_id",
				"provider_post_id",
				"provider_operation_id",
			],
			content: ["provider_effects", "error"],
			behavioral: [
				"claimed_at",
				"request_may_have_been_sent_at",
				"completed_at",
			],
			operational: [
				"state",
				"lease_expires_at",
				"provider_disposition",
				"provider_state",
			],
		},
	},
	"postgres:public.publish_outbox": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "operation_id", "organization_id", "post_id"],
			content: ["payload", "last_error"],
			behavioral: ["available_at", "claimed_at", "dispatched_at", "created_at"],
			operational: ["kind", "status", "attempts"],
		},
	},
	"postgres:public.qr_codes": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "public_id", "organization_id", "scope_key"],
			content: ["label"],
			network_identifier: ["ref_url_id"],
			behavioral: ["scan_count", "created_at", "updated_at"],
			operational: ["campaign_key"],
		},
	},
	"postgres:public.queue_failures": {
		subjectLocator: "shared_organizations",
		columns: {
			subject_identifier: [
				"id",
				"message_id",
				"organization_ids",
				"workspace_ids",
				"user_ids",
				"contact_ids",
				"account_ids",
				"operation_id",
				"payload_key_id",
			],
			content: ["queue_name", "error", "replay_error"],
			network_identifier: ["payload_ciphertext"],
			behavioral: [
				"payload_redacted_at",
				"created_at",
				"replay_requested_at",
				"resolved_at",
			],
			operational: [
				"failure_kind",
				"status",
				"attempts",
				"payload_expires_at",
				"purge_at",
				"replay_claim_token",
				"replay_claim_expires_at",
			],
		},
	},
	"postgres:public.queue_schedules": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			content: ["name"],
			behavioral: ["created_at", "updated_at"],
			operational: ["slots", "is_default"],
		},
	},
	"postgres:public.recycling_occurrences": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"operation_id",
				"config_id",
				"organization_id",
				"post_id",
			],
			content: ["error"],
			behavioral: ["created_at", "completed_at"],
			operational: ["scheduled_for", "status"],
		},
	},
	"postgres:public.ref_urls": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"slug",
				"landing_page_id",
				"automation_id",
			],
			content: ["destination_type"],
			network_identifier: ["destination_url"],
			behavioral: ["created_at", "updated_at"],
			operational: ["uses", "enabled"],
		},
	},
	"postgres:public.retention_drain_runs": {
		subjectLocator: "none",
		columns: {
			non_personal: [
				"handler_id",
				"status",
				"lease_token",
				"lease_expires_at",
				"cursor_due_at",
				"cursor_row_id",
				"last_started_at",
				"last_finished_at",
				"rows_last_run",
				"backlog_oldest_due_at",
				"consecutive_more_due",
				"last_error_code",
			],
		},
	},
	"postgres:public.segments": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["name", "description"],
			behavioral: ["member_count", "created_at", "updated_at"],
			sensitive: ["filter"],
			operational: ["is_dynamic"],
		},
	},
	"postgres:public.short_link_configs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			network_identifier: ["domain"],
			behavioral: ["created_at", "updated_at"],
			operational: [
				"mode",
				"provider",
				"provider_config_version",
				"credential_version",
			],
		},
	},
	"postgres:public.short_link_credentials": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			credential: ["api_key_ciphertext"],
			behavioral: ["created_at", "retired_at"],
			operational: ["provider", "version", "state"],
		},
	},
	"postgres:public.short_links": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"post_id",
			],
			content: [
				"creation_last_error",
				"click_sync_last_error",
				"click_sync_last_error_class",
			],
			network_identifier: ["original_url", "short_code", "short_url"],
			behavioral: [
				"creation_started_at",
				"creation_completed_at",
				"click_count",
				"last_click_sync_at",
				"next_click_sync_at",
				"click_sync_generation",
				"click_sync_lease_expires_at",
				"click_sync_started_at",
				"click_sync_attempts",
				"created_at",
			],
			operational: [
				"provider",
				"provider_config_version",
				"credential_version",
				"provider_ref",
				"creation_status",
				"creation_fence",
			],
		},
	},
	"postgres:public.signatures": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["name", "content"],
			behavioral: ["created_at", "updated_at"],
			operational: ["is_default", "position"],
		},
	},
	"postgres:public.social_account_sync_state": {
		subjectLocator: "account",
		columns: {
			subject_identifier: [
				"id",
				"social_account_id",
				"organization_id",
				"scope_key",
			],
			content: ["last_error", "last_error_class", "consecutive_errors"],
			behavioral: [
				"last_sync_at",
				"last_post_found_at",
				"next_sync_at",
				"poll_started_at",
				"rate_limit_reset_at",
				"last_error_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"platform",
				"enabled",
				"poll_generation",
				"poll_lease_expires_at",
				"poll_interval_sec",
				"consecutive_empty_polls",
				"sync_cursor",
				"rate_limit_remaining",
				"total_posts_synced",
				"total_sync_runs",
			],
		},
	},
	"postgres:public.social_accounts": {
		subjectLocator: "account",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"platform_account_id",
				"webhook_account_id",
				"workspace_id",
				"scope_key",
			],
			direct_identifier: ["username", "display_name", "avatar_url"],
			credential: ["access_token", "refresh_token"],
			content: ["metadata", "disconnect_reason", "scheduling_preferences"],
			behavioral: [
				"disconnect_requested_at",
				"disconnected_at",
				"connected_at",
				"updated_at",
			],
			sensitive: ["scopes"],
			operational: [
				"platform",
				"token_version",
				"token_expires_at",
				"lifecycle_status",
			],
		},
	},
	"postgres:public.storage_credentials": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "location_id", "organization_id"],
			credential: ["access_key_id", "secret_access_key"],
			content: ["last_error_code"],
			behavioral: [
				"last_tested_at",
				"activated_at",
				"retired_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"version",
				"state",
				"probe_token",
				"probe_lease_expires_at",
			],
		},
	},
	"postgres:public.storage_locations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			network_identifier: [
				"endpoint",
				"bucket",
				"key_prefix",
				"force_path_style",
			],
			behavioral: ["activated_at", "retired_at", "created_at"],
			operational: ["provider", "region"],
		},
	},
	"postgres:public.stripe_events": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"object_id",
				"customer_id",
				"subscription_id",
			],
			content: ["payload", "last_error", "last_error_class"],
			financial: ["stripe_created_at"],
			behavioral: [
				"received_at",
				"processed_at",
				"manual_review_at",
				"operator_retry_requested_at",
				"updated_at",
			],
			operational: [
				"type",
				"status",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.subscription_checkout_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			credential: ["stripe_checkout_url"],
			content: ["last_error"],
			financial: ["stripe_customer_id", "stripe_checkout_session_id"],
			behavioral: ["created_at", "updated_at", "completed_at"],
			operational: [
				"status",
				"idempotency_key",
				"lease_token",
				"lease_expires_at",
				"session_expires_at",
				"attempts",
			],
		},
	},
	"postgres:public.subscription_lists": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["name", "description"],
			behavioral: ["created_at", "updated_at"],
			operational: ["channel"],
		},
	},
	"postgres:public.tags": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["name", "color"],
			behavioral: ["created_at"],
		},
	},
	"postgres:public.telegram_connection_challenges": {
		subjectLocator: "account",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"api_key_id",
				"authority_session_id",
				"workspace_id",
				"scope_key",
				"chat_id",
				"account_id",
			],
			direct_identifier: ["chat_title"],
			behavioral: ["created_at", "completed_at"],
			operational: ["initial_workspace_scope", "status", "expires_at"],
		},
	},
	"postgres:public.tenant_deletion_jobs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["organization_id"],
			content: ["audit_snapshot", "cleanup_payload", "last_error"],
			behavioral: [
				"requested_by",
				"requested_at",
				"updated_at",
				"aged_alerted_at",
				"operator_retry_requested_at",
				"completed_at",
			],
			operational: [
				"status",
				"attempts",
				"next_attempt_at",
				"lease_expires_at",
				"lease_token",
			],
		},
	},
	"postgres:public.tenant_deletion_steps": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			content: ["last_error"],
			behavioral: ["created_at", "updated_at", "completed_at"],
			operational: [
				"step_key",
				"status",
				"cursor",
				"rows_deleted",
				"attempts",
				"lease_token",
				"lease_expires_at",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.thread_executions": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"thread_group_id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"lease_id",
			],
			behavioral: ["created_at", "updated_at"],
			operational: [
				"status",
				"lease_expires_at",
				"current_position",
				"attempts",
				"failed_position",
				"failure",
			],
		},
	},
	"postgres:public.token_refresh_operations": {
		subjectLocator: "account",
		columns: {
			subject_identifier: ["account_id", "operation_id"],
			content: ["last_error"],
			behavioral: [
				"started_at",
				"request_may_have_been_sent_at",
				"completed_at",
				"updated_at",
			],
			operational: [
				"state",
				"fencing_token",
				"source_token_version",
				"attempts",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.tool_jobs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			content: [
				"request_ciphertext",
				"result_ciphertext",
				"error_ciphertext",
				"error_code",
			],
			behavioral: [
				"last_enqueued_at",
				"request_may_have_been_sent_at",
				"completed_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"kind",
				"status",
				"usage_reservation_id",
				"attempts",
				"lease_token",
				"next_attempt_at",
				"lease_expires_at",
				"deadline_at",
				"purge_at",
			],
		},
	},
	"postgres:public.usage_buckets": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id", "billing_period_id"],
			financial: [
				"metric",
				"period_start",
				"period_end",
				"quota_mode",
				"included_units",
				"committed_units",
				"reserved_units",
			],
			behavioral: ["created_at", "updated_at"],
			operational: ["revision"],
		},
	},
	"postgres:public.usage_reservation_carryovers": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["organization_id"],
			network_identifier: ["source_reservation_id", "successor_bucket_id"],
			behavioral: ["created_at"],
		},
	},
	"postgres:public.usage_reservations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: ["id", "organization_id"],
			network_identifier: ["bucket_id"],
			financial: ["units", "committed_units"],
			content: ["write_off_reason", "write_off_evidence"],
			behavioral: [
				"reserved_at",
				"request_may_have_been_sent_at",
				"written_off_at",
				"finalized_at",
			],
			operational: [
				"idempotency_key",
				"state",
				"disposition",
				"response_status",
				"source",
			],
		},
	},
	"postgres:public.user_preferences": {
		subjectLocator: "user",
		columns: {
			subject_identifier: ["id", "user_id"],
			behavioral: ["created_at", "updated_at"],
			operational: ["timezone", "language"],
		},
	},
	"postgres:public.webhook_deliveries": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"webhook_event_id",
				"webhook_id",
				"organization_id",
				"dispatch_lease_id",
			],
			content: ["manual_review_reason", "error"],
			behavioral: [
				"created_at",
				"claimed_at",
				"request_may_have_been_sent_at",
				"completed_at",
				"response_time_ms",
				"manual_review_until",
				"operator_intervened_at",
				"operator_retry_requested_at",
				"next_dispatch_at",
				"last_enqueued_at",
				"updated_at",
			],
			operational: [
				"status",
				"attempts",
				"repair_attempts",
				"repair_deadline_at",
				"lease_token",
				"lease_expires_at",
				"status_code",
				"next_attempt_at",
				"dispatch_lease_expires_at",
				"dispatch_attempts",
			],
		},
	},
	"postgres:public.webhook_endpoints": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"workspace_id",
				"scope_key",
				"secret_key_id",
			],
			credential: ["secret_ciphertext"],
			network_identifier: ["url"],
			behavioral: ["events", "created_at", "updated_at"],
			operational: ["enabled"],
		},
	},
	"postgres:public.webhook_events": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"occurrence_id",
				"organization_id",
				"workspace_id",
				"scope_key",
			],
			content: ["payload"],
			behavioral: ["event", "created_at"],
		},
	},
	"postgres:public.webhook_logs": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"webhook_id",
				"webhook_event_id",
				"delivery_id",
				"organization_id",
			],
			content: ["error"],
			behavioral: ["response_time_ms", "created_at"],
			operational: [
				"attempt_ordinal",
				"attempt_kind",
				"outcome",
				"status_code",
			],
		},
	},
	"postgres:public.whatsapp_phone_numbers": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"social_account_id",
				"provider_number_id",
				"telnyx_order_id",
				"wa_phone_number_id",
			],
			direct_identifier: ["phone_number"],
			financial: [
				"stripe_phone_subscription_id",
				"stripe_subscription_item_id",
				"monthly_cost_cents",
			],
			behavioral: ["country", "created_at", "updated_at"],
			operational: ["provider", "status", "verification_method"],
		},
	},
	"postgres:public.whatsapp_phone_billing_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"stripe_customer_id",
				"stripe_checkout_session_id",
				"stripe_subscription_id",
				"stripe_subscription_item_id",
				"stripe_latest_invoice_id",
				"idempotency_key",
			],
			content: ["last_error"],
			financial: ["desired_quantity", "applied_quantity"],
			behavioral: [
				"request_may_have_been_sent_at",
				"applied_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"state",
				"revision",
				"lease_token",
				"lease_expires_at",
				"attempts",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.whatsapp_phone_billing_attempts": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"organization_id",
				"phone_billing_operation_id",
				"stripe_customer_id",
				"stripe_checkout_session_id",
				"stripe_subscription_id",
				"stripe_subscription_item_id",
				"stripe_latest_invoice_id",
				"idempotency_key",
			],
			content: ["provider_evidence"],
			financial: ["desired_quantity", "prior_applied_quantity"],
			behavioral: [
				"request_may_have_been_sent_at",
				"created_at",
				"resolved_at",
			],
			operational: ["status", "revision"],
		},
	},
	"postgres:public.whatsapp_phone_provisioning_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"phone_number_id",
				"organization_id",
				"idempotency_key_hash",
				"request_hash",
				"source_account_id",
				"source_waba_id",
			],
			direct_identifier: ["verified_name"],
			credential: ["stripe_checkout_url"],
			content: ["last_error"],
			financial: ["stripe_checkout_session_id"],
			behavioral: [
				"request_may_have_been_sent_at",
				"detail_redacted_at",
				"created_at",
				"updated_at",
			],
			operational: [
				"usage_reservation_id",
				"status",
				"phase",
				"lease_token",
				"lease_expires_at",
				"attempts",
				"next_attempt_at",
				"detail_expires_at",
			],
		},
	},
	"postgres:public.whatsapp_phone_release_operations": {
		subjectLocator: "organization",
		columns: {
			subject_identifier: [
				"id",
				"phone_number_id",
				"organization_id",
				"source_account_id",
				"authority_key_id",
				"authority_principal_id",
				"authority_user_id",
				"authority_member_id",
				"authority_session_id",
				"authority_workspace_id",
			],
			credential: ["access_token_ciphertext"],
			content: ["reason", "last_error"],
			financial: ["stripe_status"],
			behavioral: [
				"authority_admitted_at",
				"authority_revoked_at",
				"request_may_have_been_sent_at",
				"requested_at",
				"completed_at",
				"updated_at",
			],
			operational: [
				"usage_reservation_id",
				"authority_principal_type",
				"authority_requires_all_workspace_scope",
				"authority_credential_version",
				"authority_revision",
				"prior_phone_status",
				"status",
				"phase",
				"meta_status",
				"telnyx_status",
				"source_token_version",
				"lease_token",
				"lease_expires_at",
				"attempts",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.workspace_erasure_jobs": {
		subjectLocator: "workspace",
		columns: {
			subject_identifier: [
				"workspace_id",
				"organization_id",
				"scope_key",
				"erasure_operation_id",
			],
			content: ["audit_snapshot", "last_error"],
			behavioral: [
				"requested_by",
				"requested_at",
				"updated_at",
				"aged_alerted_at",
				"operator_retry_requested_at",
				"completed_at",
			],
			operational: [
				"status",
				"attempts",
				"next_attempt_at",
				"lease_token",
				"lease_expires_at",
			],
		},
	},
	"postgres:public.workspace_erasure_steps": {
		subjectLocator: "workspace",
		columns: {
			subject_identifier: [
				"id",
				"workspace_id",
				"organization_id",
				"scope_key",
			],
			content: ["last_error"],
			behavioral: ["created_at", "updated_at", "completed_at"],
			operational: [
				"step_key",
				"status",
				"cursor",
				"rows_deleted",
				"attempts",
				"lease_token",
				"lease_expires_at",
				"next_attempt_at",
			],
		},
	},
	"postgres:public.workspace_tombstones": {
		subjectLocator: "workspace",
		columns: {
			subject_identifier: [
				"workspace_id",
				"organization_id",
				"erasure_operation_id",
			],
			behavioral: ["erased_at"],
		},
	},
	"postgres:public.workspaces": {
		subjectLocator: "workspace",
		columns: {
			subject_identifier: ["id", "organization_id", "slug"],
			content: ["name", "description"],
			behavioral: [
				"archived_at",
				"erasure_requested_at",
				"created_at",
				"updated_at",
			],
			operational: ["lifecycle_status", "revision"],
		},
	},
} as const satisfies Record<string, PostgresPrivacyFieldClassification>;
