export const platformColors: Record<string, string> = {
	twitter: "bg-neutral-800",
	instagram: "bg-gradient-to-br from-purple-600 to-pink-500",
	linkedin: "bg-blue-700",
	facebook: "bg-blue-600",
	youtube: "bg-red-600",
	tiktok: "bg-neutral-900 border border-border",
	pinterest: "bg-red-700",
	threads: "bg-neutral-800",
	mastodon: "bg-purple-600",
	bluesky: "bg-blue-500",
	reddit: "bg-orange-600",
	snapchat: "bg-yellow-400",
	whatsapp: "bg-green-600",
	telegram: "bg-blue-500",
	discord: "bg-indigo-600",
	googlebusiness: "bg-blue-500",
	sms: "bg-emerald-600",
	slack: "bg-fuchsia-700",
	beehiiv: "bg-amber-500",
	convertkit: "bg-blue-600",
	mailchimp: "bg-yellow-500",
	listmonk: "bg-orange-700",
};

export const platformLabels: Record<string, string> = {
	twitter: "X / Twitter",
	instagram: "Instagram",
	linkedin: "LinkedIn",
	facebook: "Facebook",
	youtube: "YouTube",
	tiktok: "TikTok",
	pinterest: "Pinterest",
	threads: "Threads",
	mastodon: "Mastodon",
	bluesky: "Bluesky",
	reddit: "Reddit",
	snapchat: "Snapchat",
	whatsapp: "WhatsApp",
	telegram: "Telegram",
	discord: "Discord",
	googlebusiness: "Google Business",
	sms: "SMS",
	slack: "Slack",
	beehiiv: "Beehiiv",
	convertkit: "Kit (ConvertKit)",
	mailchimp: "Mailchimp",
	listmonk: "Listmonk",
};

export const platformAvatars: Record<string, string> = {
	twitter: "X",
	instagram: "IG",
	linkedin: "in",
	facebook: "f",
	youtube: "YT",
	tiktok: "TT",
	pinterest: "P",
	threads: "T",
	mastodon: "M",
	bluesky: "BS",
	reddit: "R",
	snapchat: "S",
	whatsapp: "WA",
	telegram: "TG",
	discord: "D",
	googlebusiness: "G",
	sms: "SM",
	slack: "SL",
	beehiiv: "BH",
	convertkit: "KIT",
	mailchimp: "MC",
	listmonk: "LM",
};

export const platformDescriptions: Record<string, string> = {
	twitter: "Sign in with X",
	instagram: "Connect your Instagram account",
	facebook: "Sign in and select a Page",
	linkedin: "Sign in and select a profile",
	youtube: "Sign in with Google",
	tiktok: "Sign in with TikTok",
	pinterest: "Sign in and select a Board",
	reddit: "Sign in with Reddit",
	threads: "Sign in with Threads",
	snapchat: "Sign in and select a Profile",
	googlebusiness: "Sign in and select a Location",
	mastodon: "Sign in with Mastodon",
	bluesky: "Handle and app password",
	telegram: "Connect via bot code",
	discord: "Connect an Incoming Webhook",
	whatsapp: "Connect a Cloud API number",
	sms: "Connect a Twilio sender",
	slack: "Connect an Incoming Webhook",
	beehiiv: "Connect a publication API key",
	convertkit: "Connect a Kit API v4 key",
	mailchimp: "Connect a datacenter-scoped API key",
	listmonk: "Connect a self-hosted instance",
};

export type PlatformConnectionType =
	| "oauth"
	| "credentials"
	| "bot"
	| "dialog"
	| "instance_oauth"
	| "coming_soon";

export const platformConnectionType: Record<string, PlatformConnectionType> = {
	twitter: "oauth",
	instagram: "dialog",
	facebook: "oauth",
	linkedin: "oauth",
	youtube: "oauth",
	tiktok: "oauth",
	pinterest: "oauth",
	reddit: "oauth",
	threads: "oauth",
	snapchat: "oauth",
	googlebusiness: "oauth",
	mastodon: "instance_oauth",
	bluesky: "credentials",
	telegram: "bot",
	discord: "credentials",
	whatsapp: "credentials",
	sms: "credentials",
	slack: "credentials",
	beehiiv: "credentials",
	convertkit: "credentials",
	mailchimp: "credentials",
	listmonk: "credentials",
};

export const secondarySelectionPlatforms = new Set([
	"facebook",
	"linkedin",
	"pinterest",
	"googlebusiness",
	"snapchat",
]);
