export const platformColors: Record<string, string> = {
  twitter: "bg-neutral-800",
  instagram: "bg-gradient-to-br from-purple-600 to-pink-500",
  linkedin: "bg-blue-700",
  facebook: "bg-blue-600",
  youtube: "bg-red-600",
  tiktok: "bg-neutral-900 border border-border",
  pinterest: "bg-red-700",
  threads: "bg-neutral-800",
  mastodon: "bg-purple-600",
  bluesky: "bg-blue-500",
  reddit: "bg-orange-600",
  snapchat: "bg-yellow-400",
  whatsapp: "bg-green-600",
  telegram: "bg-blue-500",
  discord: "bg-indigo-600",
  googlebusiness: "bg-blue-500",
  sms: "bg-emerald-600",
};

export const platformLabels: Record<string, string> = {
  twitter: "X / Twitter",
  instagram: "Instagram",
  linkedin: "LinkedIn",
  facebook: "Facebook",
  youtube: "YouTube",
  tiktok: "TikTok",
  pinterest: "Pinterest",
  threads: "Threads",
  mastodon: "Mastodon",
  bluesky: "Bluesky",
  reddit: "Reddit",
  snapchat: "Snapchat",
  whatsapp: "WhatsApp",
  telegram: "Telegram",
  discord: "Discord",
  googlebusiness: "Google Business",
  sms: "SMS",
};

export const platformAvatars: Record<string, string> = {
  twitter: "X",
  instagram: "IG",
  linkedin: "in",
  facebook: "f",
  youtube: "YT",
  tiktok: "TT",
  pinterest: "P",
  threads: "T",
  mastodon: "M",
  bluesky: "BS",
  reddit: "R",
  snapchat: "S",
  whatsapp: "WA",
  telegram: "TG",
  discord: "D",
  googlebusiness: "G",
  sms: "SM",
};

export const platformDescriptions: Record<string, string> = {
  twitter: "Available on demand",
  instagram: "Connect your Instagram account",
  facebook: "Sign in and select a Page",
  linkedin: "Sign in and select a profile",
  youtube: "Sign in with Google",
  tiktok: "Sign in with TikTok",
  pinterest: "Sign in and select a Board",
  reddit: "Sign in with Reddit",
  threads: "Sign in with Threads",
  snapchat: "Sign in and select a Profile",
  googlebusiness: "Sign in and select a Location",
  mastodon: "Sign in with Mastodon",
  bluesky: "Handle and app password",
  telegram: "Connect via bot code",
  discord: "Available on demand",
  whatsapp: "Available on demand",
  sms: "Available on demand",
};

export type PlatformConnectionType = "oauth" | "credentials" | "bot" | "dialog" | "coming_soon";

export const platformConnectionType: Record<string, PlatformConnectionType> = {
  twitter: "coming_soon",
  instagram: "dialog",
  facebook: "oauth",
  linkedin: "oauth",
  youtube: "oauth",
  tiktok: "oauth",
  pinterest: "oauth",
  reddit: "oauth",
  threads: "oauth",
  snapchat: "oauth",
  googlebusiness: "oauth",
  mastodon: "oauth",
  bluesky: "credentials",
  telegram: "bot",
  discord: "coming_soon",
  whatsapp: "coming_soon",
  sms: "coming_soon",
};

export const secondarySelectionPlatforms = new Set([
  "facebook",
  "linkedin",
  "pinterest",
  "googlebusiness",
  "snapchat",
]);
