import { AUTH_IDENTITY_INVARIANT_CONTRACTS } from "../src/provisioning-contracts";

const activeOwner = AUTH_IDENTITY_INVARIANT_CONTRACTS.activeOrganizationOwner;
const activeMemberUser = AUTH_IDENTITY_INVARIANT_CONTRACTS.activeMemberUser;
const memberOwner =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.memberOwnerAndCredentialExit;
const memberInvitationInvalidation =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.memberInvitationAuthorityInvalidation;
const principalCleanup =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.userDashboardPrincipalCleanup;
const credentialRotation =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.userBanCredentialRotation;
const impersonationRevocation =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.administratorImpersonationRevocation;
const originatingSessionRevocation =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.originatingSessionImpersonationRevocation;
const invitationCredentialFence =
	AUTH_IDENTITY_INVARIANT_CONTRACTS.invitationIssuerCredentialFence;
const statementBreak = "--> statement-breakpoint";

function identifier(value: string): string {
	return `"${value.replaceAll('"', '""')}"`;
}

function qualified(schema: string, name: string): string {
	return `${identifier(schema)}.${identifier(name)}`;
}

/**
 * Source of truth for auth functions and triggers that Drizzle cannot model.
 * Historical migrations remain immutable consumers; new baselines and live
 * catalog verification consume this renderer instead of reading numbered SQL.
 */
export function renderAuthIdentityInvariantSql(): string {
	return `${[
		`CREATE OR REPLACE FUNCTION ${qualified(activeOwner.functionSchema, activeOwner.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_active_organization_owner$",
		"BEGIN",
		"\tIF NEW.lifecycle_status = 'active' AND NOT EXISTS (",
		"\t\tSELECT 1",
		"\t\tFROM auth.member AS owner_member",
		'\t\tWHERE owner_member."organizationId" = NEW.id',
		"\t\t\tAND 'owner' = ANY(string_to_array(replace(owner_member.role, ' ', ''), ','))",
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'an active organization must have at least one owner',",
		"\t\t\tDETAIL = NEW.id;",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_active_organization_owner$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(activeOwner.triggerName)} ON ${qualified(activeOwner.tableSchema, activeOwner.tableName)};`,
		statementBreak,
		`CREATE CONSTRAINT TRIGGER ${identifier(activeOwner.triggerName)}`,
		'AFTER INSERT OR UPDATE OF "lifecycle_status"',
		`ON ${qualified(activeOwner.tableSchema, activeOwner.tableName)}`,
		"DEFERRABLE INITIALLY DEFERRED",
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(activeOwner.functionSchema, activeOwner.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(activeMemberUser.functionSchema, activeMemberUser.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_active_member_user$",
		"DECLARE",
		"\tmember_user_banned boolean;",
		"\tmember_user_ban_expires timestamptz;",
		"BEGIN",
		'\tSELECT member_user.banned, member_user."banExpires"',
		"\tINTO member_user_banned, member_user_ban_expires",
		'\tFROM auth."user" AS member_user',
		'\tWHERE member_user.id = NEW."userId"',
		"\tFOR SHARE;",
		"",
		"\tIF NOT FOUND",
		"\t\tOR (member_user_banned IS TRUE",
		"\t\t\tAND (member_user_ban_expires IS NULL OR member_user_ban_expires > statement_timestamp()))",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'members may only be added for active users',",
		'\t\t\tDETAIL = NEW."userId";',
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_active_member_user$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(activeMemberUser.triggerName)} ON ${qualified(activeMemberUser.tableSchema, activeMemberUser.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(activeMemberUser.triggerName)}`,
		`BEFORE INSERT ON ${qualified(activeMemberUser.tableSchema, activeMemberUser.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(activeMemberUser.functionSchema, activeMemberUser.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(memberOwner.functionSchema, memberOwner.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_owner_invariant$",
		"DECLARE",
		"\torganization_state text;",
		"\towner_exit boolean := false;",
		"\tmembership_exit boolean := false;",
		"BEGIN",
		"\tIF TG_OP = 'INSERT' THEN",
		"\t\t-- Check before the tuple exists. If tenant erasure already owns the",
		"\t\t-- organization row this waits for its commit, observes tombstoned state,",
		"\t\t-- and prevents a late FK-valid membership from reviving local access.",
		"\t\tSELECT organization_row.lifecycle_status",
		"\t\tINTO organization_state",
		"\t\tFROM auth.organization AS organization_row",
		'\t\tWHERE organization_row.id = NEW."organizationId"',
		"\t\tFOR SHARE;",
		"\t\tIF NOT FOUND OR organization_state <> 'active' THEN",
		"\t\t\tRAISE EXCEPTION USING",
		"\t\t\t\tERRCODE = '23514',",
		"\t\t\t\tMESSAGE = 'members may only be added to active organizations',",
		'\t\t\t\tDETAIL = NEW."organizationId";',
		"\t\tEND IF;",
		"\t\tRETURN NEW;",
		"\tEND IF;",
		"",
		"\tmembership_exit := TG_OP = 'DELETE';",
		"\towner_exit := membership_exit",
		"\t\tAND 'owner' = ANY(string_to_array(replace(OLD.role, ' ', ''), ','));",
		"\tIF TG_OP = 'UPDATE' THEN",
		'\t\tmembership_exit := NEW."organizationId" IS DISTINCT FROM OLD."organizationId";',
		"\t\towner_exit := 'owner' = ANY(string_to_array(replace(OLD.role, ' ', ''), ','))",
		"\t\t\tAND (",
		"\t\t\t\tmembership_exit",
		"\t\t\t\tOR NOT ('owner' = ANY(string_to_array(replace(NEW.role, ' ', ''), ',')))",
		"\t\t\t);",
		"\tEND IF;",
		"",
		"\tIF owner_exit THEN",
		"\t\t-- A row-level BEFORE trigger begins after PostgreSQL has locked OLD's",
		"\t\t-- member tuple. Keep the universally enforceable order aligned with",
		"\t\t-- identity and tenant deletion: member -> advisory -> organization.",
		"\t\tPERFORM pg_advisory_xact_lock(hashtext('relayapi:org-owner:' || OLD.\"organizationId\"));",
		"",
		"\t\t-- The no-op parent update is an MVCC serialization fence. Under",
		"\t\t-- REPEATABLE READ/SERIALIZABLE, a waiter with a stale snapshot aborts instead",
		"\t\t-- of validating against pre-lock owner state; READ COMMITTED sees the winner.",
		"\t\tUPDATE auth.organization AS organization_row",
		"\t\tSET lifecycle_status = organization_row.lifecycle_status",
		'\t\tWHERE organization_row.id = OLD."organizationId"',
		"\t\tRETURNING organization_row.lifecycle_status INTO organization_state;",
		"",
		"\t\t-- Durable organization erasure marks the tenant non-active before deleting",
		"\t\t-- it. Do not make its cascading member deletion preserve an owner.",
		"\t\tIF FOUND AND organization_state = 'active' AND NOT EXISTS (",
		"\t\t\tSELECT 1",
		"\t\t\tFROM auth.member AS other_member",
		'\t\t\tWHERE other_member."organizationId" = OLD."organizationId"',
		"\t\t\t\tAND other_member.id <> OLD.id",
		"\t\t\t\tAND 'owner' = ANY(string_to_array(replace(other_member.role, ' ', ''), ','))",
		"\t\t) THEN",
		"\t\t\tRAISE EXCEPTION USING",
		"\t\t\t\tERRCODE = '23514',",
		"\t\t\t\tMESSAGE = 'an active organization must retain at least one owner',",
		'\t\t\t\tDETAIL = OLD."organizationId";',
		"\t\tEND IF;",
		"\tEND IF;",
		"",
		"\t-- Credential/session state changes in the same statement as the membership",
		"\t-- exit. A rejected invariant or later statement failure rolls these back.",
		"\tIF membership_exit THEN",
		"\t\tUPDATE auth.apikey AS key_row",
		'\t\tSET enabled = false, "updatedAt" = now()',
		"\t\tFROM public.organization_principals AS principal_row",
		'\t\tWHERE key_row."principalId" = principal_row.id',
		'\t\t\tAND key_row."organizationId" = principal_row.organization_id',
		'\t\t\tAND principal_row.organization_id = OLD."organizationId"',
		"\t\t\tAND principal_row.member_id = OLD.id;",
		"",
		"\t\tDELETE FROM public.invite_tokens AS token_row",
		"\t\tUSING public.organization_principals AS principal_row",
		"\t\tWHERE token_row.created_by_principal_id = principal_row.id",
		"\t\t\tAND token_row.organization_id = principal_row.organization_id",
		'\t\t\tAND principal_row.organization_id = OLD."organizationId"',
		"\t\t\tAND principal_row.member_id = OLD.id;",
		"",
		"\t\tDELETE FROM public.principal_workspace_grants AS grant_row",
		"\t\tUSING public.organization_principals AS principal_row",
		"\t\tWHERE grant_row.principal_id = principal_row.id",
		"\t\t\tAND grant_row.organization_id = principal_row.organization_id",
		'\t\t\tAND principal_row.organization_id = OLD."organizationId"',
		"\t\t\tAND principal_row.member_id = OLD.id;",
		"",
		"\t\tUPDATE public.organization_principals AS principal_row",
		"\t\tSET lifecycle_status = 'disabled',",
		"\t\t\tdisabled_at = COALESCE(principal_row.disabled_at, now()),",
		"\t\t\tupdated_at = now(),",
		"\t\t\tmember_id = NULL",
		'\t\tWHERE principal_row.organization_id = OLD."organizationId"',
		"\t\t\tAND principal_row.member_id = OLD.id;",
		"",
		"\t\tUPDATE auth.session",
		'\t\tSET "activeOrganizationId" = NULL, "updatedAt" = now()',
		'\t\tWHERE "userId" = OLD."userId"',
		'\t\t\tAND "activeOrganizationId" = OLD."organizationId";',
		"\tEND IF;",
		"",
		"\tRETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;",
		"END;",
		"$relay_owner_invariant$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(memberOwner.triggerName)} ON ${qualified(memberOwner.tableSchema, memberOwner.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(memberOwner.triggerName)}`,
		'BEFORE INSERT OR DELETE OR UPDATE OF "role", "organizationId"',
		`ON ${qualified(memberOwner.tableSchema, memberOwner.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(memberOwner.functionSchema, memberOwner.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(memberInvitationInvalidation.functionSchema, memberInvitationInvalidation.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_invalidate_member_invitation_authority$",
		"BEGIN",
		"\tIF TG_OP = 'UPDATE'",
		'\t\tAND NEW."organizationId" IS NOT DISTINCT FROM OLD."organizationId"',
		"\t\tAND NEW.role IS NOT DISTINCT FROM OLD.role",
		"\tTHEN",
		"\t\tRETURN NEW;",
		"\tEND IF;",
		"",
		"\t-- A pending -> accepted update owns the invitation row as its",
		"\t-- linearization point. Do not wait in the reverse member -> invitation",
		"\t-- order. If any other operation owns a pending row, abort this authority",
		"\t-- change so the caller must retry after that row is observable.",
		"\tUPDATE auth.invitation AS invitation_row",
		"\tSET status = 'canceled'",
		"\tWHERE invitation_row.id IN (",
		"\t\tSELECT pending_invitation.id",
		"\t\tFROM auth.invitation AS pending_invitation",
		'\t\tWHERE pending_invitation."inviterId" = OLD."userId"',
		'\t\t\tAND pending_invitation."organizationId" = OLD."organizationId"',
		"\t\t\tAND pending_invitation.status = 'pending'",
		"\t\tFOR UPDATE SKIP LOCKED",
		"\t);",
		"\tIF EXISTS (",
		"\t\tSELECT 1",
		"\t\tFROM auth.invitation AS pending_invitation",
		'\t\tWHERE pending_invitation."inviterId" = OLD."userId"',
		'\t\t\tAND pending_invitation."organizationId" = OLD."organizationId"',
		"\t\t\tAND pending_invitation.status = 'pending'",
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '40001',",
		"\t\t\tMESSAGE = 'invitation authority changed concurrently; retry membership mutation',",
		'\t\t\tDETAIL = OLD."organizationId";',
		"\tEND IF;",
		"\tRETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;",
		"END;",
		"$relay_invalidate_member_invitation_authority$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(memberInvitationInvalidation.triggerName)} ON ${qualified(memberInvitationInvalidation.tableSchema, memberInvitationInvalidation.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(memberInvitationInvalidation.triggerName)}`,
		'BEFORE DELETE OR UPDATE OF "role", "organizationId"',
		`ON ${qualified(memberInvitationInvalidation.tableSchema, memberInvitationInvalidation.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(memberInvitationInvalidation.functionSchema, memberInvitationInvalidation.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(principalCleanup.functionSchema, principalCleanup.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_retire_dashboard_principals$",
		"BEGIN",
		"\tUPDATE auth.apikey AS key_row",
		'\tSET enabled = false, "updatedAt" = now()',
		"\tFROM public.organization_principals AS principal_row, auth.member AS member_row",
		'\tWHERE key_row."principalId" = principal_row.id',
		'\t\tAND key_row."organizationId" = principal_row.organization_id',
		"\t\tAND principal_row.member_id = member_row.id",
		'\t\tAND member_row."userId" = OLD.id;',
		"",
		"\tDELETE FROM public.invite_tokens AS token_row",
		"\tUSING public.organization_principals AS principal_row, auth.member AS member_row",
		"\tWHERE token_row.created_by_principal_id = principal_row.id",
		"\t\tAND token_row.organization_id = principal_row.organization_id",
		"\t\tAND principal_row.member_id = member_row.id",
		'\t\tAND member_row."userId" = OLD.id;',
		"",
		"\tDELETE FROM public.principal_workspace_grants AS grant_row",
		"\tUSING public.organization_principals AS principal_row, auth.member AS member_row",
		"\tWHERE grant_row.principal_id = principal_row.id",
		"\t\tAND grant_row.organization_id = principal_row.organization_id",
		"\t\tAND principal_row.member_id = member_row.id",
		'\t\tAND member_row."userId" = OLD.id;',
		"",
		"\tUPDATE public.organization_principals AS principal_row",
		"\tSET lifecycle_status = 'disabled',",
		"\t\tdisabled_at = COALESCE(principal_row.disabled_at, now()),",
		"\t\tupdated_at = now(),",
		"\t\tmember_id = NULL",
		"\tFROM auth.member AS member_row",
		"\tWHERE principal_row.member_id = member_row.id",
		'\t\tAND member_row."userId" = OLD.id;',
		"\tRETURN OLD;",
		"END;",
		"$relay_retire_dashboard_principals$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(principalCleanup.triggerName)} ON ${qualified(principalCleanup.tableSchema, principalCleanup.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(principalCleanup.triggerName)}`,
		`BEFORE DELETE ON ${qualified(principalCleanup.tableSchema, principalCleanup.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(principalCleanup.functionSchema, principalCleanup.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(credentialRotation.functionSchema, credentialRotation.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_rotate_user_credential_version$",
		"BEGIN",
		"\tIF (TG_OP = 'INSERT'",
		"\t\t\tAND NEW.banned IS TRUE",
		'\t\t\tAND (NEW."banExpires" IS NULL OR NEW."banExpires" > statement_timestamp()))',
		"\t\tOR (TG_OP = 'UPDATE'",
		"\t\t\tAND (OLD.banned IS DISTINCT FROM TRUE",
		'\t\t\t\tOR (OLD."banExpires" IS NOT NULL AND OLD."banExpires" <= statement_timestamp()))',
		"\t\t\tAND NEW.banned IS TRUE",
		'\t\t\tAND (NEW."banExpires" IS NULL OR NEW."banExpires" > statement_timestamp()))',
		"\tTHEN",
		'\t\tNEW."credentialVersion" := gen_random_uuid()::text;',
		"",
		"\t\t-- Avoid a user-row/invitation-row lock inversion with an acceptance",
		"\t\t-- already in flight. Locked rows are left inert by the generation",
		"\t\t-- mismatch and can be removed by normal retention/cleanup later.",
		"\t\tUPDATE auth.invitation AS invitation_row",
		"\t\tSET status = 'canceled'",
		"\t\tWHERE invitation_row.id IN (",
		"\t\t\tSELECT pending_invitation.id",
		"\t\t\tFROM auth.invitation AS pending_invitation",
		'\t\t\tWHERE pending_invitation."inviterId" = NEW.id',
		"\t\t\t\tAND pending_invitation.status = 'pending'",
		"\t\t\tFOR UPDATE SKIP LOCKED",
		"\t\t);",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_rotate_user_credential_version$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(credentialRotation.triggerName)} ON ${qualified(credentialRotation.tableSchema, credentialRotation.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(credentialRotation.triggerName)}`,
		'BEFORE INSERT OR UPDATE OF "banned", "banExpires"',
		`ON ${qualified(credentialRotation.tableSchema, credentialRotation.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(credentialRotation.functionSchema, credentialRotation.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(impersonationRevocation.functionSchema, impersonationRevocation.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_revoke_administrator_impersonation$",
		"DECLARE",
		"\tactor_id text;",
		"BEGIN",
		"\tIF TG_OP = 'DELETE' THEN",
		"\t\tactor_id := OLD.id;",
		"\tELSIF (NEW.banned IS TRUE",
		'\t\t\tAND (NEW."banExpires" IS NULL OR NEW."banExpires" > statement_timestamp()))',
		"\t\tOR NOT ('admin' = ANY(string_to_array(replace(COALESCE(NEW.role, ''), ' ', ''), ',')))",
		"\tTHEN",
		"\t\tactor_id := NEW.id;",
		"\tELSE",
		"\t\tRETURN NEW;",
		"\tEND IF;",
		"",
		"\tDELETE FROM auth.session AS impersonation_session",
		'\tWHERE impersonation_session."impersonatedBy" = actor_id;',
		"\tIF TG_OP = 'DELETE' THEN",
		"\t\tRETURN OLD;",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_revoke_administrator_impersonation$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(impersonationRevocation.triggerName)} ON ${qualified(impersonationRevocation.tableSchema, impersonationRevocation.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(impersonationRevocation.triggerName)}`,
		'AFTER DELETE OR UPDATE OF "role", "banned", "banExpires"',
		`ON ${qualified(impersonationRevocation.tableSchema, impersonationRevocation.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(impersonationRevocation.functionSchema, impersonationRevocation.functionName)}();`,
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(originatingSessionRevocation.functionSchema, originatingSessionRevocation.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_revoke_session_derived_impersonation$",
		"BEGIN",
		'\tIF OLD."impersonatedBy" IS NOT NULL THEN',
		"\t\tRETURN OLD;",
		"\tEND IF;",
		"",
		"\tDELETE FROM auth.session AS derived_impersonation_session",
		'\tWHERE derived_impersonation_session."impersonatedBy" = OLD."userId";',
		"\tRETURN OLD;",
		"END;",
		"$relay_revoke_session_derived_impersonation$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(originatingSessionRevocation.triggerName)} ON ${qualified(originatingSessionRevocation.tableSchema, originatingSessionRevocation.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(originatingSessionRevocation.triggerName)}`,
		`AFTER DELETE ON ${qualified(originatingSessionRevocation.tableSchema, originatingSessionRevocation.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(originatingSessionRevocation.functionSchema, originatingSessionRevocation.functionName)}();`,
		statementBreak,
		"",
		"-- Existing impersonation rows do not retain their originating session ID.",
		"-- Fail secure at rollout by clearing every row whose provenance cannot be proven.",
		"DELETE FROM auth.session AS impersonation_session",
		'WHERE impersonation_session."impersonatedBy" IS NOT NULL;',
		statementBreak,
		"",
		`CREATE OR REPLACE FUNCTION ${qualified(invitationCredentialFence.functionSchema, invitationCredentialFence.functionName)}()`,
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, auth",
		"AS $relay_invitation_issuer_credential_generation$",
		"DECLARE",
		"\tissuer_credential_version text;",
		"\tissuer_banned boolean;",
		"\tissuer_ban_expires timestamptz;",
		"\tissuer_member_role text;",
		"BEGIN",
		"\tIF TG_OP = 'UPDATE' AND (",
		'\t\tNEW."inviterId" IS DISTINCT FROM OLD."inviterId"',
		'\t\tOR NEW."issuerCredentialVersion" IS DISTINCT FROM OLD."issuerCredentialVersion"',
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'invitation issuer authority is immutable',",
		"\t\t\tDETAIL = NEW.id;",
		"\tEND IF;",
		"",
		"\tIF TG_OP = 'INSERT' THEN",
		'\t\tSELECT issuer_user."credentialVersion", issuer_user.banned, issuer_user."banExpires", issuer_member.role',
		"\t\tINTO issuer_credential_version, issuer_banned, issuer_ban_expires, issuer_member_role",
		'\t\tFROM auth."user" AS issuer_user',
		"\t\tJOIN auth.member AS issuer_member",
		'\t\t\tON issuer_member."userId" = issuer_user.id',
		'\t\t\tAND issuer_member."organizationId" = NEW."organizationId"',
		"\t\tJOIN auth.organization AS issuer_organization",
		'\t\t\tON issuer_organization.id = issuer_member."organizationId"',
		"\t\t\tAND issuer_organization.lifecycle_status = 'active'",
		'\t\tWHERE issuer_user.id = NEW."inviterId"',
		"\t\tFOR SHARE OF issuer_user, issuer_member, issuer_organization;",
		"",
		"\t\tIF NOT FOUND",
		"\t\t\tOR (issuer_banned IS TRUE",
		"\t\t\t\tAND (issuer_ban_expires IS NULL OR issuer_ban_expires > statement_timestamp()))",
		"\t\tTHEN",
		"\t\t\tRAISE EXCEPTION USING",
		"\t\t\t\tERRCODE = '23514',",
		"\t\t\t\tMESSAGE = 'invitation issuer is not active',",
		"\t\t\t\tDETAIL = NEW.id;",
		"\t\tEND IF;",
		"",
		"\t\tIF NOT (",
		"\t\t\t'owner' = ANY(string_to_array(replace(issuer_member_role, ' ', ''), ','))",
		"\t\t\tOR (",
		"\t\t\t\t'admin' = ANY(string_to_array(replace(issuer_member_role, ' ', ''), ','))",
		"\t\t\t\tAND NOT ('owner' = ANY(string_to_array(replace(COALESCE(NEW.role, ''), ' ', ''), ',')))",
		"\t\t\t)",
		"\t\t) THEN",
		"\t\t\tRAISE EXCEPTION USING",
		"\t\t\t\tERRCODE = '23514',",
		"\t\t\t\tMESSAGE = 'invitation issuer lacks role authority',",
		"\t\t\t\tDETAIL = NEW.id;",
		"\t\tEND IF;",
		"",
		'\t\tNEW."issuerCredentialVersion" := issuer_credential_version;',
		"\tELSIF OLD.status = 'pending' AND NEW.status = 'accepted' THEN",
		'\t\tSELECT issuer_user."credentialVersion", issuer_user.banned, issuer_user."banExpires"',
		"\t\tINTO issuer_credential_version, issuer_banned, issuer_ban_expires",
		'\t\tFROM auth."user" AS issuer_user',
		'\t\tWHERE issuer_user.id = NEW."inviterId"',
		"\t\tFOR SHARE;",
		"",
		"\t\tIF NOT FOUND",
		"\t\t\tOR (issuer_banned IS TRUE",
		"\t\t\t\tAND (issuer_ban_expires IS NULL OR issuer_ban_expires > statement_timestamp()))",
		'\t\t\tOR NEW."issuerCredentialVersion" IS DISTINCT FROM issuer_credential_version',
		"\t\tTHEN",
		"\t\t\tRETURN NULL;",
		"\t\tEND IF;",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_invitation_issuer_credential_generation$;",
		statementBreak,
		`DROP TRIGGER IF EXISTS ${identifier(invitationCredentialFence.triggerName)} ON ${qualified(invitationCredentialFence.tableSchema, invitationCredentialFence.tableName)};`,
		statementBreak,
		`CREATE TRIGGER ${identifier(invitationCredentialFence.triggerName)}`,
		'BEFORE INSERT OR UPDATE OF "status", "inviterId", "issuerCredentialVersion"',
		`ON ${qualified(invitationCredentialFence.tableSchema, invitationCredentialFence.tableName)}`,
		"FOR EACH ROW",
		`EXECUTE FUNCTION ${qualified(invitationCredentialFence.functionSchema, invitationCredentialFence.functionName)}();`,
		statementBreak,
	].join("\n")}\n`;
}

if (import.meta.main) {
	process.stdout.write(renderAuthIdentityInvariantSql());
}
