const statementBreak = "--> statement-breakpoint";

/**
 * Source-owned trigger contract for the legal-hold receipt. Drizzle can model
 * its tuple checks and partial uniqueness, but it cannot express target
 * validation against two differently shaped roots or transition immutability.
 */
export function renderErasureHoldInvariantSql(): string {
	return `${[
		"CREATE OR REPLACE FUNCTION public.relayapi_guard_erasure_hold()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public, auth",
		"AS $relay_guard_erasure_hold$",
		"DECLARE",
		"\tis_redaction boolean := false;",
		"BEGIN",
		"\tIF TG_OP = 'INSERT' THEN",
		"\t\tIF NEW.subject_kind = 'organization' THEN",
		"\t\t\tPERFORM 1",
		"\t\t\tFROM auth.organization AS organization_row",
		"\t\t\tWHERE organization_row.id = NEW.subject_id",
		"\t\t\tFOR KEY SHARE;",
		"\t\t\tIF NEW.subject_id <> NEW.organization_tombstone_id OR NOT FOUND THEN",
		"\t\t\t\tRAISE EXCEPTION USING",
		"\t\t\t\t\tERRCODE = '23503',",
		"\t\t\t\t\tMESSAGE = 'erasure hold organization target does not exist',",
		"\t\t\t\t\tDETAIL = NEW.subject_id;",
		"\t\t\tEND IF;",
		"\t\tELSIF NEW.subject_kind = 'workspace' THEN",
		"\t\t\tPERFORM 1",
		"\t\t\tFROM public.workspaces AS workspace_row",
		"\t\t\tWHERE workspace_row.id = NEW.subject_id",
		"\t\t\t\tAND workspace_row.organization_id = NEW.organization_tombstone_id",
		"\t\t\tFOR KEY SHARE;",
		"\t\t\tIF NOT FOUND THEN",
		"\t\t\t\tRAISE EXCEPTION USING",
		"\t\t\t\t\tERRCODE = '23503',",
		"\t\t\t\t\tMESSAGE = 'erasure hold workspace target does not exist in the organization',",
		"\t\t\t\t\tDETAIL = NEW.subject_id;",
		"\t\t\tEND IF;",
		"\t\tELSE",
		"\t\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid erasure hold subject kind';",
		"\t\tEND IF;",
		"\t\tRETURN NEW;",
		"\tEND IF;",
		"",
		"\tIF NEW.id IS DISTINCT FROM OLD.id",
		"\t\tOR NEW.subject_kind IS DISTINCT FROM OLD.subject_kind",
		"\t\tOR NEW.subject_id IS DISTINCT FROM OLD.subject_id",
		"\t\tOR NEW.organization_tombstone_id IS DISTINCT FROM OLD.organization_tombstone_id",
		"\t\tOR NEW.reason_code IS DISTINCT FROM OLD.reason_code",
		"\t\tOR NEW.placed_at IS DISTINCT FROM OLD.placed_at",
		"\t\tOR NEW.created_at IS DISTINCT FROM OLD.created_at",
		"\t\tOR NEW.released_at IS DISTINCT FROM OLD.released_at",
		"\t\t\tAND OLD.released_at IS NOT NULL",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'erasure hold identity and transition timestamps are immutable';",
		"\tEND IF;",
		"",
		"\tis_redaction := OLD.released_at IS NOT NULL",
		"\t\tAND OLD.evidence_redacted_at IS NULL",
		"\t\tAND NEW.evidence_redacted_at IS NOT NULL;",
		"\tIF is_redaction THEN",
		"\t\tIF NEW.reason_summary <> '[redacted]'",
		"\t\t\tOR NEW.legal_authority_ref <> '[redacted]'",
		"\t\t\tOR NEW.placed_by <> '[redacted]'",
		"\t\t\tOR NEW.released_by <> '[redacted]'",
		"\t\t\tOR NEW.release_reason_summary <> '[redacted]'",
		"\t\t\tOR NEW.evidence_ciphertext IS NOT NULL",
		"\t\t\tOR NEW.released_at IS DISTINCT FROM OLD.released_at",
		"\t\tTHEN",
		"\t\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid erasure hold redaction transition';",
		"\t\tEND IF;",
		"\t\tRETURN NEW;",
		"\tEND IF;",
		"",
		"\tIF NEW.reason_summary IS DISTINCT FROM OLD.reason_summary",
		"\t\tOR NEW.legal_authority_ref IS DISTINCT FROM OLD.legal_authority_ref",
		"\t\tOR NEW.placed_by IS DISTINCT FROM OLD.placed_by",
		"\t\tOR NEW.evidence_ciphertext IS DISTINCT FROM OLD.evidence_ciphertext",
		"\t\tOR NEW.evidence_redacted_at IS DISTINCT FROM OLD.evidence_redacted_at",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'erasure hold placement fields are immutable';",
		"\tEND IF;",
		"",
		"\tIF OLD.released_at IS NULL THEN",
		"\t\tIF NEW.released_at IS NULL",
		"\t\t\tOR NEW.released_by IS NULL",
		"\t\t\tOR NEW.release_reason_summary IS NULL",
		"\t\tTHEN",
		"\t\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'erasure hold may only be updated by a complete release transition';",
		"\t\tEND IF;",
		"\tELSE",
		"\t\tIF NEW.released_by IS DISTINCT FROM OLD.released_by",
		"\t\t\tOR NEW.release_reason_summary IS DISTINCT FROM OLD.release_reason_summary",
		"\t\tTHEN",
		"\t\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'erasure hold release may occur only once';",
		"\t\tEND IF;",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_guard_erasure_hold$;",
		statementBreak,
		"DROP TRIGGER IF EXISTS relayapi_erasure_hold_guard ON public.erasure_holds;",
		statementBreak,
		"CREATE TRIGGER relayapi_erasure_hold_guard",
		"BEFORE INSERT OR UPDATE ON public.erasure_holds",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.relayapi_guard_erasure_hold();",
		statementBreak,
		"",
		"CREATE OR REPLACE FUNCTION public.relayapi_prevent_held_root_delete()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public",
		"AS $relay_prevent_held_root_delete$",
		"BEGIN",
		"\tIF TG_TABLE_SCHEMA = 'auth' THEN",
		"\t\tIF EXISTS (",
		"\t\t\tSELECT 1 FROM public.erasure_holds AS hold",
		"\t\t\tWHERE hold.organization_tombstone_id = OLD.id",
		"\t\t\t\tAND hold.released_at IS NULL",
		"\t\t) THEN",
		"\t\t\tRAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'organization deletion is paused by an active erasure hold', DETAIL = OLD.id;",
		"\t\tEND IF;",
		"\tELSE",
		"\t\tIF EXISTS (",
		"\t\t\tSELECT 1 FROM public.erasure_holds AS hold",
		"\t\t\tWHERE hold.released_at IS NULL",
		"\t\t\t\tAND hold.organization_tombstone_id = OLD.organization_id",
		"\t\t\t\tAND (",
		"\t\t\t\t\t(hold.subject_kind = 'organization' AND hold.subject_id = OLD.organization_id)",
		"\t\t\t\t\tOR (hold.subject_kind = 'workspace' AND hold.subject_id = OLD.id)",
		"\t\t\t\t)",
		"\t\t) THEN",
		"\t\t\tRAISE EXCEPTION USING ERRCODE = '23503', MESSAGE = 'workspace deletion is paused by an active erasure hold', DETAIL = OLD.id;",
		"\t\tEND IF;",
		"\tEND IF;",
		"\tRETURN OLD;",
		"END;",
		"$relay_prevent_held_root_delete$;",
		statementBreak,
		"DROP TRIGGER IF EXISTS relayapi_organization_hold_delete_guard ON auth.organization;",
		statementBreak,
		"CREATE TRIGGER relayapi_organization_hold_delete_guard",
		"BEFORE DELETE ON auth.organization",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.relayapi_prevent_held_root_delete();",
		statementBreak,
		"DROP TRIGGER IF EXISTS relayapi_workspace_hold_delete_guard ON public.workspaces;",
		statementBreak,
		"CREATE TRIGGER relayapi_workspace_hold_delete_guard",
		"BEFORE DELETE ON public.workspaces",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.relayapi_prevent_held_root_delete();",
		statementBreak,
	].join("\n")}\n`;
}

if (import.meta.main) {
	process.stdout.write(renderErasureHoldInvariantSql());
}
