const statementBreak = "--> statement-breakpoint";

/**
 * Routing definitions and credential identities are insert-only. The only
 * legal mutations are location activation/retirement, credential state
 * transitions, probe leases, and ciphertext re-encryption.
 */
export function renderStorageLocationInvariantSql(): string {
	return `${[
		statementBreak,
		"CREATE OR REPLACE FUNCTION public.enforce_storage_location_immutability()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public",
		"AS $relay_storage_location_immutability$",
		"BEGIN",
		"\tIF NEW.organization_id IS DISTINCT FROM OLD.organization_id",
		"\t\tOR NEW.provider IS DISTINCT FROM OLD.provider",
		"\t\tOR NEW.endpoint IS DISTINCT FROM OLD.endpoint",
		"\t\tOR NEW.bucket IS DISTINCT FROM OLD.bucket",
		"\t\tOR NEW.region IS DISTINCT FROM OLD.region",
		"\t\tOR NEW.key_prefix IS DISTINCT FROM OLD.key_prefix",
		"\t\tOR NEW.force_path_style IS DISTINCT FROM OLD.force_path_style",
		"\t\tOR NEW.created_at IS DISTINCT FROM OLD.created_at",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'storage location routing fields are immutable; insert a new location';",
		"\tEND IF;",
		"",
		"\tIF OLD.activated_at IS NOT NULL AND NEW.activated_at IS DISTINCT FROM OLD.activated_at THEN",
		"\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'storage location activation is immutable';",
		"\tEND IF;",
		"\tIF OLD.retired_at IS NOT NULL AND NEW.retired_at IS DISTINCT FROM OLD.retired_at THEN",
		"\t\tRAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'retired storage locations are terminal';",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_storage_location_immutability$;",
		statementBreak,
		"",
		"DROP TRIGGER IF EXISTS enforce_storage_location_immutability ON public.storage_locations;",
		statementBreak,
		"CREATE TRIGGER enforce_storage_location_immutability",
		"BEFORE UPDATE ON public.storage_locations",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.enforce_storage_location_immutability();",
		statementBreak,
		"",
		"CREATE OR REPLACE FUNCTION public.enforce_storage_credential_transition()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public",
		"AS $relay_storage_credential_transition$",
		"BEGIN",
		"\tIF NEW.location_id IS DISTINCT FROM OLD.location_id",
		"\t\tOR NEW.organization_id IS DISTINCT FROM OLD.organization_id",
		"\t\tOR NEW.version IS DISTINCT FROM OLD.version",
		"\t\tOR NEW.created_at IS DISTINCT FROM OLD.created_at",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'storage credential identity is immutable; insert a new version';",
		"\tEND IF;",
		"",
		"\tIF NEW.state IS DISTINCT FROM OLD.state AND NOT (",
		"\t\t(OLD.state = 'staged' AND NEW.state IN ('active', 'failed'))",
		"\t\tOR (OLD.state = 'active' AND NEW.state = 'retired')",
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = format('invalid storage credential transition: %s -> %s', OLD.state, NEW.state);",
		"\tEND IF;",
		"\tNEW.updated_at := statement_timestamp();",
		"\tRETURN NEW;",
		"END;",
		"$relay_storage_credential_transition$;",
		statementBreak,
		"",
		"DROP TRIGGER IF EXISTS enforce_storage_credential_transition ON public.storage_credentials;",
		statementBreak,
		"CREATE TRIGGER enforce_storage_credential_transition",
		"BEFORE UPDATE ON public.storage_credentials",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.enforce_storage_credential_transition();",
		statementBreak,
	].join("\n")}\n`;
}

if (import.meta.main) {
	process.stdout.write(renderStorageLocationInvariantSql());
}
