const statementBreak = "--> statement-breakpoint";

/**
 * Render the parts of billing-period authority that Drizzle cannot express:
 * GiST temporal exclusion, a deferrable exact-window FK for period splits, and
 * transition guards for immutable financial snapshots.
 */
export function renderBillingPeriodInvariantSql(): string {
	return `${[
		statementBreak,
		"ALTER TABLE public.usage_buckets",
		"\tALTER CONSTRAINT usage_buckets_billing_period_window_fk",
		"\tDEFERRABLE INITIALLY IMMEDIATE;",
		statementBreak,
		"",
		"ALTER TABLE public.billing_periods",
		"\tADD CONSTRAINT billing_periods_invoice_org_fk",
		"\tFOREIGN KEY (invoice_id, organization_id)",
		"\tREFERENCES public.invoices (id, organization_id)",
		"\tON UPDATE NO ACTION ON DELETE RESTRICT;",
		statementBreak,
		"",
		"ALTER TABLE public.billing_periods",
		"\tADD CONSTRAINT billing_periods_live_window_excl",
		"\tEXCLUDE USING gist (",
		"\t\torganization_id WITH =,",
		"\t\ttstzrange(period_start, period_end, '[)') WITH &&",
		"\t)",
		"\tWHERE (state <> 'void');",
		statementBreak,
		"",
		"CREATE OR REPLACE FUNCTION public.enforce_billing_period_authority()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public",
		"AS $relay_billing_period_transition$",
		"BEGIN",
		"\tIF NEW.id IS DISTINCT FROM OLD.id",
		"\t\tOR NEW.organization_id IS DISTINCT FROM OLD.organization_id",
		"\t\tOR NEW.source IS DISTINCT FROM OLD.source",
		"\t\tOR NEW.billable IS DISTINCT FROM OLD.billable",
		"\t\tOR NEW.quota_mode IS DISTINCT FROM OLD.quota_mode",
		"\t\tOR NEW.provider_cycle_anchor IS DISTINCT FROM OLD.provider_cycle_anchor",
		"\t\tOR NEW.period_start IS DISTINCT FROM OLD.period_start",
		"\t\tOR NEW.stripe_customer_id IS DISTINCT FROM OLD.stripe_customer_id",
		"\t\tOR NEW.stripe_subscription_id IS DISTINCT FROM OLD.stripe_subscription_id",
		"\t\tOR NEW.stripe_product_id IS DISTINCT FROM OLD.stripe_product_id",
		"\t\tOR NEW.stripe_price_id IS DISTINCT FROM OLD.stripe_price_id",
		"\t\tOR NEW.stripe_price_role IS DISTINCT FROM OLD.stripe_price_role",
		"\t\tOR NEW.rate_card_version IS DISTINCT FROM OLD.rate_card_version",
		"\t\tOR NEW.tax_behavior IS DISTINCT FROM OLD.tax_behavior",
		"\t\tOR NEW.tax_code IS DISTINCT FROM OLD.tax_code",
		"\t\tOR NEW.discountable IS DISTINCT FROM OLD.discountable",
		"\t\tOR NEW.cycle_allowance IS DISTINCT FROM OLD.cycle_allowance",
		"\t\tOR NEW.included_units IS DISTINCT FROM OLD.included_units",
		"\t\tOR NEW.price_per_thousand_units_cents IS DISTINCT FROM OLD.price_per_thousand_units_cents",
		"\t\tOR NEW.base_price_cents IS DISTINCT FROM OLD.base_price_cents",
		"\t\tOR NEW.currency IS DISTINCT FROM OLD.currency",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'billing period authority fields are immutable; split the period instead';",
		"\tEND IF;",
		"",
		"\tIF NEW.period_end IS DISTINCT FROM OLD.period_end",
		"\t\tAND NOT (OLD.state = 'open'",
		"\t\t\tAND NEW.period_end < OLD.period_end",
		"\t\t\tAND NEW.period_end > OLD.period_start)",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'an open billing period may only be shortened';",
		"\tEND IF;",
		"",
		"\tIF NEW.release_count IS DISTINCT FROM OLD.release_count",
		"\t\tAND NOT (OLD.state = 'claimed'",
		"\t\t\tAND NEW.state = 'released'",
		"\t\t\tAND OLD.release_count = 0",
		"\t\t\tAND NEW.release_count = 1)",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'a billing period permits exactly one operator release';",
		"\tEND IF;",
		"",
		"\tIF OLD.state = 'claimed'",
		"\t\tAND NEW.state = 'released'",
		"\t\tAND OLD.release_count <> 0",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'billing period reclaim has already been used';",
		"\tEND IF;",
		"",
		"\tIF NEW.state IS DISTINCT FROM OLD.state AND NOT (",
		"\t\t(OLD.state = 'open' AND NEW.state IN ('closed', 'void'))",
		"\t\tOR (OLD.state = 'closed' AND NEW.state IN ('claimed', 'void'))",
		"\t\tOR (OLD.state = 'claimed' AND NEW.state IN ('settled', 'released', 'written_off'))",
		"\t\tOR (OLD.state = 'released' AND NEW.state IN ('closed', 'void'))",
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = format('invalid billing period transition: %s -> %s', OLD.state, NEW.state);",
		"\tEND IF;",
		"",
		"\tIF NOT (OLD.state = 'released' AND NEW.state = 'closed')",
		"\t\tAND (",
		"\t\t\t(OLD.committed_units_snapshot IS NOT NULL",
		"\t\t\t\tAND NEW.committed_units_snapshot IS DISTINCT FROM OLD.committed_units_snapshot)",
		"\t\t\tOR (OLD.effective_included_units_snapshot IS NOT NULL",
		"\t\t\t\tAND NEW.effective_included_units_snapshot IS DISTINCT FROM OLD.effective_included_units_snapshot)",
		"\t\t\tOR (OLD.overage_units_snapshot IS NOT NULL",
		"\t\t\t\tAND NEW.overage_units_snapshot IS DISTINCT FROM OLD.overage_units_snapshot)",
		"\t\t\tOR (OLD.amount_cents_snapshot IS NOT NULL",
		"\t\t\t\tAND NEW.amount_cents_snapshot IS DISTINCT FROM OLD.amount_cents_snapshot)",
		"\t\t\tOR (OLD.closed_at IS NOT NULL AND NEW.closed_at IS DISTINCT FROM OLD.closed_at)",
		"\t\t\tOR (OLD.claimed_at IS NOT NULL AND NEW.claimed_at IS DISTINCT FROM OLD.claimed_at)",
		"\t\t\tOR (OLD.settled_at IS NOT NULL AND NEW.settled_at IS DISTINCT FROM OLD.settled_at)",
		"\t\t\tOR (OLD.released_at IS NOT NULL AND NEW.released_at IS DISTINCT FROM OLD.released_at)",
		"\t\t\tOR (OLD.written_off_at IS NOT NULL AND NEW.written_off_at IS DISTINCT FROM OLD.written_off_at)",
		"\t\t\tOR (OLD.write_off_reason IS NOT NULL AND NEW.write_off_reason IS DISTINCT FROM OLD.write_off_reason)",
		"\t\t\tOR (OLD.write_off_evidence IS NOT NULL AND NEW.write_off_evidence IS DISTINCT FROM OLD.write_off_evidence)",
		"\t\t\tOR (OLD.voided_at IS NOT NULL AND NEW.voided_at IS DISTINCT FROM OLD.voided_at)",
		"\t\t\tOR (OLD.invoice_id IS NOT NULL AND NEW.invoice_id IS DISTINCT FROM OLD.invoice_id)",
		"\t\t\tOR (OLD.stripe_invoice_id IS NOT NULL",
		"\t\t\t\tAND NEW.stripe_invoice_id IS DISTINCT FROM OLD.stripe_invoice_id)",
		"\t\t)",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'billing period close and settlement evidence is immutable';",
		"\tEND IF;",
		"",
		"\tNEW.revision := OLD.revision + 1;",
		"\tNEW.updated_at := statement_timestamp();",
		"\tRETURN NEW;",
		"END;",
		"$relay_billing_period_transition$;",
		statementBreak,
		"",
		"DROP TRIGGER IF EXISTS enforce_billing_period_transition ON public.billing_periods;",
		statementBreak,
		"DROP TRIGGER IF EXISTS billing_periods_authority_immutable ON public.billing_periods;",
		statementBreak,
		"CREATE TRIGGER billing_periods_authority_immutable",
		"BEFORE UPDATE ON public.billing_periods",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.enforce_billing_period_authority();",
		statementBreak,
		"",
		"CREATE OR REPLACE FUNCTION public.enforce_billing_operation_attempt_authority()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public",
		"AS $relay_billing_operation_attempt$",
		"BEGIN",
		"\tIF NEW.id IS DISTINCT FROM OLD.id",
		"\t\tOR NEW.organization_id IS DISTINCT FROM OLD.organization_id",
		"\t\tOR NEW.billing_operation_id IS DISTINCT FROM OLD.billing_operation_id",
		"\t\tOR NEW.revision IS DISTINCT FROM OLD.revision",
		"\t\tOR NEW.stripe_customer_id IS DISTINCT FROM OLD.stripe_customer_id",
		"\t\tOR NEW.stripe_subscription_id IS DISTINCT FROM OLD.stripe_subscription_id",
		"\t\tOR NEW.stripe_invoice_id IS DISTINCT FROM OLD.stripe_invoice_id",
		"\t\tOR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key",
		"\t\tOR NEW.amount_cents IS DISTINCT FROM OLD.amount_cents",
		"\t\tOR NEW.currency IS DISTINCT FROM OLD.currency",
		"\t\tOR NEW.description IS DISTINCT FROM OLD.description",
		"\t\tOR NEW.created_at IS DISTINCT FROM OLD.created_at",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'billing attempt target and economic payload are immutable; create a new revision';",
		"\tEND IF;",
		"",
		"\tIF NEW.status IS DISTINCT FROM OLD.status AND NOT (",
		"\t\t(OLD.status = 'prepared' AND NEW.status IN ('requesting', 'rejected', 'written_off'))",
		"\t\tOR (OLD.status = 'requesting' AND NEW.status IN ('unknown', 'succeeded', 'rejected'))",
		"\t\tOR (OLD.status = 'unknown' AND NEW.status IN ('requesting', 'succeeded', 'rejected', 'written_off'))",
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = format('invalid billing attempt transition: %s -> %s', OLD.status, NEW.status);",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_billing_operation_attempt$;",
		statementBreak,
		"",
		"DROP TRIGGER IF EXISTS billing_operation_attempts_authority_immutable ON public.billing_operation_attempts;",
		statementBreak,
		"CREATE TRIGGER billing_operation_attempts_authority_immutable",
		"BEFORE UPDATE ON public.billing_operation_attempts",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.enforce_billing_operation_attempt_authority();",
		statementBreak,
		"",
		"CREATE OR REPLACE FUNCTION public.enforce_phone_billing_attempt_authority()",
		"RETURNS trigger",
		"LANGUAGE plpgsql",
		"SET search_path = pg_catalog, public",
		"AS $relay_phone_billing_attempt$",
		"BEGIN",
		"\tIF NEW.id IS DISTINCT FROM OLD.id",
		"\t\tOR NEW.organization_id IS DISTINCT FROM OLD.organization_id",
		"\t\tOR NEW.phone_billing_operation_id IS DISTINCT FROM OLD.phone_billing_operation_id",
		"\t\tOR NEW.revision IS DISTINCT FROM OLD.revision",
		"\t\tOR NEW.desired_quantity IS DISTINCT FROM OLD.desired_quantity",
		"\t\tOR NEW.prior_applied_quantity IS DISTINCT FROM OLD.prior_applied_quantity",
		"\t\tOR NEW.stripe_customer_id IS DISTINCT FROM OLD.stripe_customer_id",
		"\t\tOR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key",
		"\t\tOR NEW.created_at IS DISTINCT FROM OLD.created_at",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'phone billing attempt target and economic payload are immutable; create a new revision';",
		"\tEND IF;",
		"",
		"\tIF (OLD.stripe_checkout_session_id IS NOT NULL",
		"\t\t\tAND NEW.stripe_checkout_session_id IS DISTINCT FROM OLD.stripe_checkout_session_id)",
		"\t\tOR (OLD.stripe_subscription_id IS NOT NULL",
		"\t\t\tAND NEW.stripe_subscription_id IS DISTINCT FROM OLD.stripe_subscription_id)",
		"\t\tOR (OLD.stripe_subscription_item_id IS NOT NULL",
		"\t\t\tAND NEW.stripe_subscription_item_id IS DISTINCT FROM OLD.stripe_subscription_item_id)",
		"\t\tOR (OLD.stripe_latest_invoice_id IS NOT NULL",
		"\t\t\tAND NEW.stripe_latest_invoice_id IS DISTINCT FROM OLD.stripe_latest_invoice_id)",
		"\t\tOR (OLD.request_may_have_been_sent_at IS NOT NULL",
		"\t\t\tAND NEW.request_may_have_been_sent_at IS DISTINCT FROM OLD.request_may_have_been_sent_at)",
		"\t\tOR (OLD.resolved_at IS NOT NULL",
		"\t\t\tAND NEW.resolved_at IS DISTINCT FROM OLD.resolved_at)",
		"\t\tOR (OLD.provider_evidence IS NOT NULL",
		"\t\t\tAND (NEW.provider_evidence IS NULL OR NOT (NEW.provider_evidence @> OLD.provider_evidence)))",
		"\tTHEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = 'phone billing provider identity and evidence are append-only once observed';",
		"\tEND IF;",
		"",
		"\tIF NEW.status IS DISTINCT FROM OLD.status AND NOT (",
		"\t\t(OLD.status = 'prepared' AND NEW.status IN ('requesting', 'waiting_payment', 'applied', 'confirmed_not_applied', 'manual_review'))",
		"\t\tOR (OLD.status = 'requesting' AND NEW.status IN ('unknown', 'waiting_payment', 'applied', 'confirmed_not_applied', 'manual_review'))",
		"\t\tOR (OLD.status = 'unknown' AND NEW.status IN ('waiting_payment', 'applied', 'confirmed_not_applied', 'manual_review'))",
		"\t\tOR (OLD.status = 'waiting_payment' AND NEW.status IN ('unknown', 'applied', 'confirmed_not_applied', 'manual_review'))",
		"\t\tOR (OLD.status = 'manual_review' AND NEW.status IN ('applied', 'confirmed_not_applied'))",
		"\t) THEN",
		"\t\tRAISE EXCEPTION USING",
		"\t\t\tERRCODE = '23514',",
		"\t\t\tMESSAGE = format('invalid phone billing attempt transition: %s -> %s', OLD.status, NEW.status);",
		"\tEND IF;",
		"\tRETURN NEW;",
		"END;",
		"$relay_phone_billing_attempt$;",
		statementBreak,
		"",
		"DROP TRIGGER IF EXISTS whatsapp_phone_billing_attempts_authority_immutable ON public.whatsapp_phone_billing_attempts;",
		statementBreak,
		"CREATE TRIGGER whatsapp_phone_billing_attempts_authority_immutable",
		"BEFORE UPDATE ON public.whatsapp_phone_billing_attempts",
		"FOR EACH ROW",
		"EXECUTE FUNCTION public.enforce_phone_billing_attempt_authority();",
		statementBreak,
	].join("\n")}\n`;
}

if (import.meta.main) {
	process.stdout.write(renderBillingPeriodInvariantSql());
}
