/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --config=../api/wrangler.jsonc --env-file=/dev/null --include-runtime=false --env-interface=AppWorkerEnv` (hash: 2d778305a941417d36bb502ddafe3daa)
interface __BaseEnv_AppWorkerEnv {
	KV: KVNamespace;
	AVATARS_BUCKET: R2Bucket;
	PUBLIC_ASSETS: R2Bucket;
	QUEUE_RESCUE_BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	IDENTITY_DELETION_CONTRACT_VERSION: "identity-deletion-v1";
	BASELINE_GENERATION: "1";
	EMAIL_INTENTS: Service<typeof import("../api/src/index").EmailIntentEntrypoint>;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_AppWorkerEnv {}
}
interface AppWorkerEnv extends __BaseEnv_AppWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IDENTITY_DELETION_CONTRACT_VERSION" | "BASELINE_GENERATION">> {}
}
