/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --env-interface=AppWorkerEnv` (hash: 34469328ab7aced07bba756e632d6c00)
interface __BaseEnv_AppWorkerEnv {
	KV: KVNamespace;
	AVATARS_BUCKET: R2Bucket;
	PUBLIC_ASSETS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	EMAIL_QUEUE: Queue;
	IDENTITY_DELETION_CONTRACT_VERSION: "0005";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_AppWorkerEnv {}
}
interface AppWorkerEnv extends __BaseEnv_AppWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IDENTITY_DELETION_CONTRACT_VERSION">> {}
}
